#!/usr/bin/env python3
"""Flag prose naming a specific tool's absence/presence as an
evidence-limitation reason, with no owner-disclosure marker in the same
diff.

Issue #520 (row 3, refs #350): retrospective #350 found that a doc's
evidence-limitation note disclosed a session-specific runtime-tooling
fingerprint -- naming the absence of "a registered Skill invocation" and
"a generic dispatch tool" -- as the reason a prior evaluation could not be
reused, in an outward-facing artifact, without an owner decision to
disclose it (CLAUDE.md section 3's provenance-marker audit). A reviewer
bot caught it that time; this gate makes the catch deterministic.

Distinct from skills/outward-artifact-preflight/scripts/scan_provenance.py:
that script flags markers of *this artifact's own production* (a model ID,
a session URL, a "generated by" tag). This gate flags a different pattern
-- prose that names a specific tool's absence/presence as the *reason* for
a stated limitation (e.g. "because no registered Skill invocation tool was
available") -- a session-tooling fingerprint used as justification, not a
production marker. Both are non-exhaustive, keyword-based heuristics by
design (issue #520's own Acceptance Criteria Map names this as residual
risk: "a keyword/pattern list that could miss novel phrasings").

A paragraph is flagged when it combines (a) a limitation/reason cue
("no access to", "lacks access to", "absence of", "missing a", ...) with
(b) a tool-fingerprint cue (a generic internal-tooling concept: "registered
skill", "dispatch tool", "subagent", "task tool", "agent tool", "mcp
tool", "tool call", ...) in the same paragraph -- mirroring
scan_provenance.py's own same-line corroborating-context approach, scoped
to the paragraph since prose evidence-limitation notes commonly wrap
across lines in Markdown.

Disclosure marker: a `tool-fingerprint-disclosure: WAIVED: <reason>` line
anywhere in the combined corpus (PR body plus any diff-added doc text
handed to this script) -- same `WAIVED: <reason>` vocabulary as
gate_skill_audit_disclosure.py and gate_acm_issue_disclosure.py's own
waiver lines, applied to a different section.

Deliberately stdlib-only and self-contained, matching this repository's
existing .github/scripts/*.py convention of not importing across files.

Usage::

    python3 .github/scripts/gate_provenance_disclosure.py \\
        --body PR_BODY.txt --diff-added ADDED_LINES.txt [--diff-added ...]
    printf '%s' "$PR_BODY" | python3 .github/scripts/gate_provenance_disclosure.py

Exit codes:
    0  No offending paragraph in the combined corpus, or a disclosure
       marker is present.
    1  An offending paragraph exists with no disclosure marker, or a given
       file could not be read.
"""

from __future__ import annotations

import argparse
import re
import sys

_LIMITATION_CUE_RE = re.compile(
    r"\b(?:"
    r"no access to|without access to|lacks?\s+access to|lacking\s+access to|"
    r"does(?:n't| not) have access to|absence of|missing (?:a|an)\b|"
    r"not available"
    r")\b",
    re.IGNORECASE,
)

_TOOL_CUE_RE = re.compile(
    r"\b(?:"
    r"registered skill|skill invocation|dispatch tool|generic dispatch|"
    r"sub-?agent|task tool|agent tool|mcp tool|tool call"
    r")\b",
    re.IGNORECASE,
)

_WAIVER_RE = re.compile(
    r"^[ \t]*[-*]?[ \t]*`?tool-fingerprint-disclosure`?[ \t]*:[ \t]*WAIVED[ \t]*:[ \t]*\S.*$",
    re.IGNORECASE | re.MULTILINE,
)


def _paragraphs(text: str) -> list[str]:
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    return [p for p in re.split(r"\n\s*\n", normalized) if p.strip()]


def find_offending_paragraphs(text: str) -> list[str]:
    """Return every paragraph in `text` that combines a limitation/reason
    cue with a tool-fingerprint cue."""
    return [
        paragraph
        for paragraph in _paragraphs(text)
        if _LIMITATION_CUE_RE.search(paragraph) and _TOOL_CUE_RE.search(paragraph)
    ]


def has_disclosure_marker(text: str) -> bool:
    """Return True iff `text` carries a `tool-fingerprint-disclosure: WAIVED: <reason>` line."""
    return bool(_WAIVER_RE.search(text.replace("\r\n", "\n").replace("\r", "\n")))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Flag prose naming a specific tool's absence/presence as an "
        "evidence-limitation reason, with no owner-disclosure marker."
    )
    parser.add_argument(
        "--body",
        help="Path to the PR body / review-response draft text; reads standard input when omitted "
        "and no --diff-added is given.",
    )
    parser.add_argument(
        "--diff-added",
        action="append",
        default=[],
        help="Path to a file of this diff's added lines (e.g. from a changed doc); repeatable.",
    )
    args = parser.parse_args(argv)

    sources: list[str] = []
    try:
        if args.body:
            sources.append(open(args.body, encoding="utf-8").read())
        elif not args.diff_added:
            sources.append(sys.stdin.read())
        for diff_path in args.diff_added:
            sources.append(open(diff_path, encoding="utf-8").read())
    except FileNotFoundError as error:
        print(f"error: file not found: {error.filename}", file=sys.stderr)
        return 1

    corpus = "\n\n".join(sources)
    offending = find_offending_paragraphs(corpus)

    if not offending:
        print("PASS: no undisclosed tool-fingerprint evidence-limitation prose found")
        return 0

    if has_disclosure_marker(corpus):
        print("PASS: tool-fingerprint prose found, but disclosed via tool-fingerprint-disclosure: WAIVED")
        return 0

    print(
        f"FAIL: {len(offending)} paragraph(s) name a specific tool's absence/presence as an "
        "evidence-limitation reason with no owner-disclosure marker:",
        file=sys.stderr,
    )
    for paragraph in offending:
        first_line = paragraph.strip().splitlines()[0]
        print(f"  - {first_line}", file=sys.stderr)
    print(
        "Rephrase to state the limitation without naming or implying specific runtime-tool "
        "internals, or add 'tool-fingerprint-disclosure: WAIVED: <reason>' if the owner has "
        "explicitly approved disclosing it.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
