#!/usr/bin/env python3
"""Flag prose naming a specific tool's absence/presence as an
evidence-limitation reason, with no owner-disclosure marker in the same
diff.

Issue #520 (row 3, refs #350): retrospective #350 found that a doc's
evidence-limitation note named two pieces of session-specific
runtime-tooling machinery as the reason a prior evaluation could not be
reused, in an outward-facing artifact, without an owner decision to
disclose it (CLAUDE.md section 3's provenance-marker audit). A reviewer
bot caught it that time; this gate makes the catch deterministic. (This
paragraph deliberately does not reproduce the flagged phrasing verbatim --
doing so would self-trigger this very gate on this file; see the
Vocabulary section below for the actual cue words instead.)

Distinct from skills/outward-artifact-preflight/scripts/gitapex_scan_provenance.py:
that script flags markers of *this artifact's own production* (a model ID,
a session URL, a "generated by" tag). This gate flags a different pattern
-- prose that names a specific tool's absence/presence as the *reason* for
a stated limitation (e.g. "because no registered Skill invocation tool was
available") -- a session-tooling fingerprint used as justification, not a
production marker. Both are non-exhaustive, keyword-based heuristics by
design (issue #520's own Acceptance Criteria Map names this as residual
risk: "a keyword/pattern list that could miss novel phrasings").

A paragraph is flagged when it combines a limitation/reason cue with a
tool-fingerprint cue in the same paragraph -- mirroring gitapex_scan_provenance.py's
own same-line corroborating-context approach, scoped to the paragraph
since prose evidence-limitation notes commonly wrap across lines in
Markdown.

Vocabulary (non-exhaustive by design, per CLAUDE.md section 4's
"non-exhaustive instances / default-in-scope" invariant): limitation/
reason cue examples include "no access to", "lacks access to", "absence
of", "missing a", and their close variants; tool-fingerprint cue examples
include "a registered skill invocation", "a dispatch tool", "a subagent",
and "an MCP tool call", and their close variants -- see
`_LIMITATION_CUE_RE`/`_TOOL_CUE_RE` below for the exact patterns. Extend
either as new phrasings are observed, matching gitapex_scan_provenance.py's
own "add more patterns as new fingerprint shapes are observed" convention.

Both cue types are quoted above deliberately, in the same paragraph:
`find_offending_paragraphs` only counts a cue match as *live* prose when
it falls outside a short, documented-example quoted/backtick span (see
`_quoted_example_spans`/`_has_live_match` below), so a short backtick- or
quote-delimited example -- like every phrase in this paragraph -- is
excluded from matching. Issue #549 (repairs 1 and 8) documented this
gate's own PR body, and separately its own pre-redesign docstring,
self-triggering by combining both cue types as unquoted prose in one
paragraph; that cycle's fix was a narrower workaround (manually keeping
the vocabulary split across two paragraphs so no single paragraph
combined both cue types -- the literal original wording was never
committed, corrected before either commit landed, and #549's own
retrospective deliberately avoided reproducing it verbatim to avoid
re-triggering the gate on itself). Issue #978 replaces that workaround
with the quoting-aware matching implemented here, which covers future
documentation of this gate's vocabulary generally rather than only this
one docstring instance -- matching is done by filtering cue-match
*positions*, never by rewriting the paragraph text, so a documented
example can never be mistaken for surrounding whitespace and bridge two
otherwise-unrelated live words into a fabricated match (a real defect an
adversarial review round found in this issue's own first draft, which did
rewrite the text). The word-count cap on what counts as a documented
example also means a real violation cannot evade detection merely by
wrapping its *entire* clause in one long quoted span -- only a short,
bare phrase is excluded (another adversarial-review finding against the
first draft). The `tool-fingerprint-disclosure: WAIVED: <reason>` marker
below remains available as an explicit override for any case this
heuristic still misses -- known, disclosed, and accepted: a live sentence
that quotes only *one* of its two cue phrases (not the whole clause) can
still evade detection, since only the quoted half is excluded from
matching.

Disclosure marker: a `tool-fingerprint-disclosure: WAIVED: <reason>` line
anywhere in the combined corpus (PR body plus any diff-added doc text
handed to this script) -- same `WAIVED: <reason>` vocabulary as
gitapex_gate_skill_audit_disclosure.py and gitapex_gate_acm_issue_disclosure.py's own
waiver lines, applied to a different section.

Deliberately stdlib-only and self-contained, matching this repository's
existing .github/scripts/*.py convention of not importing across files.

Usage::

    python3 .github/scripts/gitapex_gate_provenance_disclosure.py \\
        --body PR_BODY.txt --diff-added ADDED_LINES.txt [--diff-added ...]
    printf '%s' "$PR_BODY" | python3 .github/scripts/gitapex_gate_provenance_disclosure.py

Exit codes:
    0  No offending paragraph in the combined corpus, or a disclosure
       marker is present.
    1  An offending paragraph exists with no disclosure marker, or a given
       file could not be read.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Non-exhaustive by design (see the module docstring's Vocabulary section
# and CLAUDE.md section 4's own "non-exhaustive instances / default-in-
# scope" invariant): these are the observed cue phrases from issue #350's
# original incidents, not a closed allowlist. Extend as new phrasings are
# observed.
_LIMITATION_CUE_RE = re.compile(
    r"\b(?:"
    r"no access to|without access to|lacks?\s+access to|lacking\s+access to|"
    r"does(?:n't| not) have access to|absence of|missing (?:a|an)\b|"
    r"not available"
    r")\b",
    re.IGNORECASE,
)

# Non-exhaustive by design, same rationale as _LIMITATION_CUE_RE above.
_TOOL_CUE_RE = re.compile(
    r"\b(?:"
    r"registered skill|skill invocation|dispatch tool|generic dispatch|"
    r"sub-?agent|task tool|agent tool|mcp tool|tool call"
    r")\b",
    re.IGNORECASE,
)

_WAIVER_RE = re.compile(
    r"^[ \t]*[-*]?[ \t]*`?tool-fingerprint-disclosure`?[ \t]*:[ \t]*WAIVED[ \t]*:[ \t]*\S.*$",
    re.IGNORECASE | re.MULTILINE,
)

# A short cue phrase inside a backtick span or a straight/curly
# double-quoted span is a documented example (as the module docstring's
# own Vocabulary paragraph uses), not a live evidence-limitation claim.
# Bounded quantifier (no unbounded backtracking); deliberately allowed to
# span an embedded newline (unlike a first draft of this pattern, which
# excluded "\n" and so missed a hard-wrapped quoted example split across
# two lines of Markdown source -- this repository's own docs/skills/evals
# convention -- reproducing the exact #549 self-trigger class this gate
# exists to fix). Still bounded to one paragraph: `_quoted_example_spans`
# below is only ever called with one already-paragraph-split string.
_QUOTED_SPAN_RE = re.compile(
    r"`[^`]{1,200}`" r'|"[^"]{1,200}"' r"|“[^”]{1,200}”",
)

# An adversarial review of issue #978's first draft (which treated a
# quoted span of any length as a documented example) found it let an
# entire offending clause evade detection by wrapping the whole sentence
# in one long quoted span -- a materially bigger bypass than the disclosed
# "quote one cue phrase for emphasis" risk. Capping what counts as a
# "documented example" at a short word count closes that: every real
# vocabulary example in this module's own docstring is a handful of words
# (`"a dispatch tool"`, `"an MCP tool call"`), while a real limitation
# clause combining both cues needs a full sentence to read naturally,
# well past this bound. See
# test_find_offending_paragraphs_still_flags_fully_quoted_violating_clause.
_MAX_QUOTED_EXAMPLE_WORDS = 6


def _paragraphs(text: str) -> list[str]:
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    return [p for p in re.split(r"\n\s*\n", normalized) if p.strip()]


def _quoted_example_spans(text: str) -> list[tuple[int, int]]:
    """Return the (start, end) offsets of every short, documented-example
    quoted/backtick span in `text` (see `_MAX_QUOTED_EXAMPLE_WORDS`)."""
    return [
        match.span()
        for match in _QUOTED_SPAN_RE.finditer(text)
        if len(match.group(0)[1:-1].split()) <= _MAX_QUOTED_EXAMPLE_WORDS
    ]


def _has_live_match(cue_re: re.Pattern[str], text: str, example_spans: list[tuple[int, int]]) -> bool:
    """True iff `cue_re` matches `text` somewhere outside every span in
    `example_spans`.

    A second adversarial-review round found that an earlier draft of this
    module *textually removed* documented-example spans before matching
    (replacing them with a single space) -- which let a whitespace-
    tolerant cue alternative (e.g. `lacks\\s+access to`) bridge across the
    removed span and fabricate a match between two words that were never
    actually adjacent in the live prose. Filtering match *positions*
    instead of rewriting the text structurally rules that class of bug
    out: nothing is ever deleted or replaced, so no new adjacency can be
    created.
    """
    for match in cue_re.finditer(text):
        if not any(start <= match.start() and match.end() <= end for start, end in example_spans):
            return True
    return False


def find_offending_paragraphs(text: str) -> list[str]:
    """Return every paragraph in `text` that combines a limitation/reason
    cue with a tool-fingerprint cue as live prose -- i.e. outside any
    short, documented-example quoted/backtick span."""
    offending = []
    for paragraph in _paragraphs(text):
        example_spans = _quoted_example_spans(paragraph)
        if _has_live_match(_LIMITATION_CUE_RE, paragraph, example_spans) and _has_live_match(
            _TOOL_CUE_RE, paragraph, example_spans
        ):
            offending.append(paragraph)
    return offending


def has_disclosure_marker(text: str) -> bool:
    """Return True iff `text` carries a `tool-fingerprint-disclosure: WAIVED: <reason>` line."""
    return bool(_WAIVER_RE.search(text.replace("\r\n", "\n").replace("\r", "\n")))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Flag prose naming a specific tool's absence/presence as an "
        "evidence-limitation reason, with no owner-disclosure marker."
    )
    parser.add_argument(
        "--body",
        help="Path to the PR body / review-response draft text; reads standard input when omitted "
        "and no --diff-added is given.",
    )
    parser.add_argument(
        "--diff-added",
        action="append",
        default=[],
        help="Path to a file of this diff's added lines (e.g. from a changed doc); repeatable.",
    )
    args = parser.parse_args(argv)

    sources: list[str] = []
    reading: str = "standard input"
    try:
        if args.body:
            reading = args.body
            sources.append(Path(args.body).read_text(encoding="utf-8"))
        elif not args.diff_added:
            sources.append(sys.stdin.buffer.read().decode("utf-8"))
        for diff_path in args.diff_added:
            reading = diff_path
            sources.append(Path(diff_path).read_text(encoding="utf-8"))
    except FileNotFoundError as error:
        print(f"error: file not found: {error.filename}", file=sys.stderr)
        return 1
    except UnicodeDecodeError as error:
        print(f"error: {reading} is not valid UTF-8: {error}", file=sys.stderr)
        return 1

    corpus = "\n\n".join(sources)
    offending = find_offending_paragraphs(corpus)

    if not offending:
        print("PASS: no undisclosed tool-fingerprint evidence-limitation prose found")
        return 0

    if has_disclosure_marker(corpus):
        print("PASS: tool-fingerprint prose found, but disclosed via tool-fingerprint-disclosure: WAIVED")
        return 0

    print(
        f"FAIL: {len(offending)} paragraph(s) name a specific tool's absence/presence as an "
        "evidence-limitation reason with no owner-disclosure marker:",
        file=sys.stderr,
    )
    for paragraph in offending:
        first_line = paragraph.strip().splitlines()[0]
        print(f"  - {first_line}", file=sys.stderr)
    print(
        "Rephrase to state the limitation without naming or implying specific runtime-tool "
        "internals, or add 'tool-fingerprint-disclosure: WAIVED: <reason>' if the owner has "
        "explicitly approved disclosing it.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
