"""Tests for the consolidated local PR-body preflight
(.github/scripts/gitapex_gate_pr_body_preflight.py, issue #1725).

Two different gate scripts -- skill-audit-disclosure (#1707) and
provenance-disclosure (#1711) -- were each tripped by the same root
cause: no single local command ran every PR-body-affecting gate together
before a create_pull_request/update_pull_request call. This suite proves
the consolidated command actually catches both original defect shapes,
not just that its own aggregation logic works in the abstract.

Sub-checks that need no git state (ascii-only, provenance-marker-scan,
provenance-disclosure) are exercised against the real sibling scripts --
issue #1711's own reconstruction in particular needs the real
gate_provenance_disclosure.py behavior, not a stand-in. The one sub-check
that needs a real git repository and this checkout's own pydantic-backed
gitapex_compute_skill_audit_flags module (skill-audit-disclosure) is
instead exercised against a small stand-in script asserting the exact
argv contract this module promises it -- test_gitapex_gate_skill_audit_
disclosure.py already covers that real gate's own git/pydantic behavior
directly, so re-deriving it here would just be a slower, duplicate copy.
"""

from __future__ import annotations

import pathlib

import gitapex_gate_pr_body_preflight as preflight
import pytest
from conftest import init_git_repo, run_git

_CLEAN_BODY = "Clean PR body.\n\nCloses #1725\n"

# Issue #1711's own reconstruction: a paragraph combining a limitation
# cue ("no access to") and a tool-fingerprint cue ("a dispatch tool") in
# the same paragraph, the exact shape that false-triggered provenance-
# disclosure in CI after the local pre-push pass had not included it.
_1711_BODY = (
    "Execution log bullet: skill-audit-disclosure found the body missing "
    "its required section, because no access to a registered skill "
    "invocation was available for a dispatch tool at the time.\n"
)


# --- check_ascii_only ---


def test_check_ascii_only_passes_clean_text() -> None:
    result = preflight.check_ascii_only(_CLEAN_BODY)
    assert result.passed
    assert not result.skipped


def test_check_ascii_only_flags_non_ascii() -> None:
    result = preflight.check_ascii_only("PR body with an em dash — here.\n")
    assert not result.passed
    assert "non-ASCII" in result.output


def test_check_ascii_only_allows_bare_tabs() -> None:
    result = preflight.check_ascii_only("col1\tcol2\n")
    assert result.passed


# --- format_report ---


def test_format_report_all_passed() -> None:
    results = [preflight.CheckResult("a", True, False, ""), preflight.CheckResult("b", True, False, "")]
    report = preflight.format_report(results)
    assert "PASS  a" in report
    assert "PASS  b" in report
    assert "all 2 run check(s) passed." in report


def test_format_report_with_failure_and_skip() -> None:
    results = [
        preflight.CheckResult("a", False, False, "FAIL: bad"),
        preflight.CheckResult("b", True, False, ""),
        preflight.CheckResult("c", False, True, "skipped reason"),
    ]
    report = preflight.format_report(results)
    assert "FAIL  a" in report
    assert "PASS  b" in report
    assert "SKIPPED  c" in report
    assert "1 of 3 check(s) FAILED: a" in report
    assert "skipped reason" in report


# --- check_provenance_marker_scan (real sibling script) ---


def test_check_provenance_marker_scan_passes_clean_body(tmp_path: pathlib.Path) -> None:
    body = tmp_path / "body.txt"
    body.write_text(_CLEAN_BODY, encoding="utf-8")
    result = preflight.check_provenance_marker_scan(body)
    assert result.passed
    assert not result.skipped


def test_check_provenance_marker_scan_flags_session_url(tmp_path: pathlib.Path) -> None:
    body = tmp_path / "body.txt"
    body.write_text(
        "Generated by claude-example-model during session https://claude.ai/code/session_01Example\n",
        encoding="utf-8",
    )
    result = preflight.check_provenance_marker_scan(body)
    assert not result.passed


def test_check_provenance_marker_scan_raises_when_sibling_missing(
    tmp_path: pathlib.Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    body = tmp_path / "body.txt"
    body.write_text(_CLEAN_BODY, encoding="utf-8")
    monkeypatch.setattr(preflight, "PROVENANCE_MARKER_SCAN", tmp_path / "does-not-exist.py")
    try:
        preflight.check_provenance_marker_scan(body)
        raise AssertionError("expected PrBodyPreflightError")
    except preflight.PrBodyPreflightError:
        pass


# --- check_provenance_disclosure (real sibling script, issue #1711) ---


def test_check_provenance_disclosure_passes_clean_body(tmp_path: pathlib.Path) -> None:
    body = tmp_path / "body.txt"
    body.write_text(_CLEAN_BODY, encoding="utf-8")
    result = preflight.check_provenance_disclosure(body, None)
    assert result.passed
    assert not result.skipped


def test_check_provenance_disclosure_reconstructs_1711_false_positive(tmp_path: pathlib.Path) -> None:
    body = tmp_path / "body.txt"
    body.write_text(_1711_BODY, encoding="utf-8")
    result = preflight.check_provenance_disclosure(body, None)
    assert not result.passed
    assert "paragraph" in result.output.lower()


def test_check_provenance_disclosure_grades_diff_added_corpus_too(tmp_path: pathlib.Path) -> None:
    body = tmp_path / "body.txt"
    body.write_text(_CLEAN_BODY, encoding="utf-8")
    corpus = "no access to a registered skill invocation for a dispatch tool\n"
    result = preflight.check_provenance_disclosure(body, corpus)
    assert not result.passed


# --- check_skill_audit_disclosure ---


def test_check_skill_audit_disclosure_skipped_without_check_diff(tmp_path: pathlib.Path) -> None:
    body = tmp_path / "body.txt"
    body.write_text(_CLEAN_BODY, encoding="utf-8")
    result = preflight.check_skill_audit_disclosure(body, None)
    assert result.skipped
    assert not result.passed


_STAND_IN_SKILL_AUDIT_GATE = """\
import sys
args = sys.argv[1:]
assert args[0] == '--check-diff'
assert args[1] == 'BASE'
assert args[2] == 'HEAD'
assert args[3] == '--body-file'
body = open(args[4]).read()
if 'RAN,' in body:
    print('FAIL: disclosure line malformed', file=sys.stderr)
    sys.exit(1)
print('PASS')
sys.exit(0)
"""


def test_check_skill_audit_disclosure_reconstructs_1707_regex_break(
    tmp_path: pathlib.Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Issue #1707: a stray comma right after "RAN" broke the real gate's
    own regex. This stand-in asserts the exact argv contract
    check_skill_audit_disclosure promises (--check-diff BASE HEAD
    --body-file PATH) and reproduces that comma-sensitive shape, so the
    test proves this module's own argv wiring surfaces a FAIL exactly
    the way the original defect would have -- and that a corrected body
    passes once fixed."""
    dummy = tmp_path / "dummy_skill_audit_gate.py"
    dummy.write_text(_STAND_IN_SKILL_AUDIT_GATE, encoding="utf-8")
    monkeypatch.setattr(preflight, "SKILL_AUDIT_DISCLOSURE", dummy)

    body_fail = tmp_path / "body_fail.txt"
    body_fail.write_text("deterministic-gate-quality: RAN, iteratively\n", encoding="utf-8")
    result = preflight.check_skill_audit_disclosure(body_fail, ("BASE", "HEAD"))
    assert not result.passed
    assert not result.skipped

    body_pass = tmp_path / "body_pass.txt"
    body_pass.write_text("deterministic-gate-quality: RAN\n", encoding="utf-8")
    result = preflight.check_skill_audit_disclosure(body_pass, ("BASE", "HEAD"))
    assert result.passed


def test_check_skill_audit_disclosure_raises_when_sibling_missing(
    tmp_path: pathlib.Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    body = tmp_path / "body.txt"
    body.write_text(_CLEAN_BODY, encoding="utf-8")
    monkeypatch.setattr(preflight, "SKILL_AUDIT_DISCLOSURE", tmp_path / "does-not-exist.py")
    try:
        preflight.check_skill_audit_disclosure(body, ("BASE", "HEAD"))
        raise AssertionError("expected PrBodyPreflightError")
    except preflight.PrBodyPreflightError:
        pass


# --- build_diff_added_corpus ---


def test_build_diff_added_corpus_extracts_added_paragraph(
    tmp_path: pathlib.Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = init_git_repo(tmp_path / "repo")
    docs_dir = repo / "docs"
    docs_dir.mkdir()
    (docs_dir / "note.md").write_text("first version\n", encoding="utf-8")
    run_git(["git", "add", "-A"], repo)
    run_git(["git", "commit", "-q", "-m", "base"], repo)
    run_git(["git", "tag", "base"], repo)

    (docs_dir / "note.md").write_text("first version\n\nsecond paragraph added\n", encoding="utf-8")
    run_git(["git", "add", "-A"], repo)
    run_git(["git", "commit", "-q", "-m", "head"], repo)

    monkeypatch.setattr(preflight, "REPO_ROOT", repo)
    corpus = preflight.build_diff_added_corpus("base", "HEAD")
    assert "second paragraph added" in corpus


def test_build_diff_added_corpus_raises_on_bad_ref(tmp_path: pathlib.Path, monkeypatch: pytest.MonkeyPatch) -> None:
    repo = init_git_repo(tmp_path / "repo")
    (repo / "README.md").write_text("hello\n", encoding="utf-8")
    run_git(["git", "add", "-A"], repo)
    run_git(["git", "commit", "-q", "-m", "init"], repo)

    monkeypatch.setattr(preflight, "REPO_ROOT", repo)
    try:
        preflight.build_diff_added_corpus("does-not-exist", "HEAD")
        raise AssertionError("expected PrBodyPreflightError")
    except preflight.PrBodyPreflightError:
        pass


# --- run_all_checks / main (end to end) ---


def test_main_exits_zero_on_clean_body(tmp_path: pathlib.Path) -> None:
    body = tmp_path / "body.txt"
    body.write_text(_CLEAN_BODY, encoding="utf-8")
    assert preflight.main(["--body", str(body)]) == 0


def test_main_exits_nonzero_reconstructing_1711(tmp_path: pathlib.Path) -> None:
    body = tmp_path / "body.txt"
    body.write_text(_1711_BODY, encoding="utf-8")
    assert preflight.main(["--body", str(body)]) == 1


def test_main_accepts_body_file_alias(tmp_path: pathlib.Path) -> None:
    body = tmp_path / "body.txt"
    body.write_text(_CLEAN_BODY, encoding="utf-8")
    assert preflight.main(["--body-file", str(body)]) == 0


def test_main_errors_on_missing_body_file(tmp_path: pathlib.Path, capsys: pytest.CaptureFixture[str]) -> None:
    exit_code = preflight.main(["--body", str(tmp_path / "does-not-exist.txt")])
    assert exit_code == 1
    assert "not found" in capsys.readouterr().err
