"""Direct-import, fetcher-injection unit suite for
hooks/gitapex_check_post_write_provenance.py (issue #878).

No test in this file makes a real network call -- the network layer is
exercised through an injected `fetcher`, the same injection style
tests/test_gitapex_check_pr_issue_acm_disclosure.py uses for its own
`opener`. `hooks` is on pyproject.toml's `pythonpath`, so this module
imports as a plain top-level module rather than via importlib.util.

Subprocess-level `.sh`-wrapper tests live in
hooks/test_gitapex_check_post_write_provenance_shell.py instead -- see
that file's own docstring for why the split, and for the pytest basename
collision the `_shell` suffix avoids.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import gitapex_check_post_write_provenance as checker
import gitapex_check_pr_issue_acm_disclosure as pr_issue_checker
import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]

_LEAKED_BODY = (
    "Refs #878\n\nGenerated by claude-example-model during session https://claude.ai/code/session_01Example99"
)


def fetcher_returning(body: str) -> Any:
    def fetcher(owner: str, repo: str, number: int, token: str) -> dict[str, str]:
        return {"body": body, "state": "open"}

    return fetcher


def payload(
    *,
    tool_name: str = "mcp__github__create_pull_request",
    tool_input: dict[str, Any] | None = None,
    tool_response: Any = None,
) -> dict[str, Any]:
    built: dict[str, Any] = {"tool_name": tool_name}
    built["tool_input"] = {"owner": "tvna", "repo": "gitapex"} if tool_input is None else tool_input
    if tool_response is not None:
        built["tool_response"] = tool_response
    return built


# --- scanner loading ------------------------------------------------------


def test_default_scanner_path_resolves_to_the_shipped_scanner() -> None:
    """The relative path this hook resolves must really exist in the
    repository tree -- a hook that silently cannot find its own scanner
    would report INDETERMINATE forever, and no unit test injecting a
    scanner_path would notice."""
    module = checker.load_provenance_scanner()
    assert callable(module.scan)


def test_missing_scanner_is_indeterminate_not_a_clean_pass(tmp_path: Path) -> None:
    with pytest.raises(checker.VerificationError) as excinfo:
        checker.load_provenance_scanner(tmp_path / "absent.py")
    assert "not found" in str(excinfo.value)


def test_unimportable_scanner_is_indeterminate_not_a_clean_pass(tmp_path: Path) -> None:
    broken = tmp_path / "broken.py"
    broken.write_text("raise RuntimeError('boom')\n", encoding="utf-8")
    with pytest.raises(checker.VerificationError) as excinfo:
        checker.load_provenance_scanner(broken)
    assert "failed to import" in str(excinfo.value)


# --- ASCII scan (outward-artifact-preflight checklist item 3) --------------


def test_an_importable_module_without_scan_is_indeterminate(tmp_path: Path) -> None:
    """A file can sit at the expected path, import cleanly, and still not be
    the scanner. Without the contract check that mismatch surfaced as an
    AttributeError from scan_body(), forwarded as a raw traceback."""
    impostor = tmp_path / "impostor.py"
    impostor.write_text("VALUE = 1\n", encoding="utf-8")
    with pytest.raises(checker.VerificationError) as excinfo:
        checker.load_provenance_scanner(impostor)
    assert "no callable scan()" in str(excinfo.value)


def test_a_non_callable_scan_attribute_is_also_rejected(tmp_path: Path) -> None:
    impostor = tmp_path / "impostor.py"
    impostor.write_text("scan = 'not a function'\n", encoding="utf-8")
    with pytest.raises(checker.VerificationError):
        checker.load_provenance_scanner(impostor)


def test_pure_ascii_body_has_no_ascii_hits() -> None:
    assert checker.scan_non_ascii("Closes #878\n\nPlain ASCII body.\t(tabbed)\r\n") == []


def test_em_dash_is_reported_by_codepoint_not_echoed() -> None:
    hits = checker.scan_non_ascii("a \u2014 b")
    assert hits == [(1, 3, "U+2014 EM DASH")]
    assert "\u2014" not in hits[0][2]


def test_every_occurrence_is_reported_with_its_own_line_and_column() -> None:
    hits = checker.scan_non_ascii("x\u00e9\nyy\u00e9")
    assert [(line, column) for line, column, _ in hits] == [(1, 2), (2, 3)]


@pytest.mark.parametrize(
    ("body", "expected"),
    [
        ("\u2028", "U+2028 LINE SEPARATOR"),
        ("\u2029", "U+2029 PARAGRAPH SEPARATOR"),
        ("\u0085", "U+0085 unnamed character"),
        ("a\u000bb", "U+000B unnamed character"),
        ("a\u000cb", "U+000C unnamed character"),
        ("a\u001eb", "U+001E unnamed character"),
    ],
)
def test_a_character_str_splitlines_would_swallow_is_still_reported(body: str, expected: str) -> None:
    """str.splitlines() splits on every one of these, consuming exactly the
    characters this scan exists to report -- a body of a single U+2028
    scanned clean before this regression was closed."""
    hits = checker.scan_non_ascii(body)
    assert [label for _, _, label in hits] == [expected]


def test_a_crlf_body_reports_nothing_extra_after_the_split_change() -> None:
    """Splitting on "\n" alone leaves a bare \r at each line's end; it must
    stay an allowed character, not become a new false positive."""
    assert checker.scan_non_ascii("line one\r\nline two\r\n") == []


def test_unnamed_codepoint_does_not_crash_the_scan() -> None:
    """A codepoint with no formal Unicode name (an unassigned/private-use
    character) must still report, not raise -- unicodedata.name() raises
    ValueError without the default argument this scan passes."""
    hits = checker.scan_non_ascii("\ue000")
    assert hits == [(1, 1, "U+E000 unnamed character")]


# --- target resolution ----------------------------------------------------


def test_number_comes_from_tool_input_on_an_update() -> None:
    resolved = checker.resolve_target(
        payload(
            tool_name="mcp__github__update_pull_request",
            tool_input={"owner": "tvna", "repo": "gitapex", "pullNumber": 42},
        )
    )
    assert resolved == ("tvna", "gitapex", 42)


def test_number_comes_from_the_response_on_a_create() -> None:
    resolved = checker.resolve_target(payload(tool_response={"number": 7}))
    assert resolved == ("tvna", "gitapex", 7)


def test_number_is_read_from_an_mcp_content_string_envelope() -> None:
    resolved = checker.resolve_target(payload(tool_response={"content": json.dumps({"number": 9})}))
    assert resolved == ("tvna", "gitapex", 9)


def test_number_is_read_from_an_mcp_text_block_list_envelope() -> None:
    resolved = checker.resolve_target(
        payload(tool_response={"content": [{"type": "text", "text": json.dumps({"number": 11})}]})
    )
    assert resolved == ("tvna", "gitapex", 11)


def test_a_non_json_text_block_falls_through_to_the_next_block() -> None:
    resolved = checker.resolve_target(
        payload(
            tool_response={
                "content": [
                    {"type": "text", "text": "not json at all"},
                    {"type": "text", "text": json.dumps({"number": 13})},
                ]
            }
        )
    )
    assert resolved == ("tvna", "gitapex", 13)


def test_a_string_number_is_accepted() -> None:
    resolved = checker.resolve_target(payload(tool_response={"number": "17"}))
    assert resolved == ("tvna", "gitapex", 17)


def test_a_boolean_number_is_rejected_not_read_as_pr_one() -> None:
    """isinstance(True, int) is True in Python, so an unguarded read would
    resolve {"number": true} to PR #1 and re-scan an unrelated artifact."""
    with pytest.raises(checker.VerificationError):
        checker.resolve_target(payload(tool_response={"number": True}))


@pytest.mark.parametrize("bad", [0, -3, "0", "abc", None, 1.5])
def test_an_implausible_number_is_rejected(bad: Any) -> None:
    with pytest.raises(checker.VerificationError):
        checker.resolve_target(payload(tool_response={"number": bad}))


def test_a_missing_owner_is_verification_error() -> None:
    with pytest.raises(checker.VerificationError) as excinfo:
        checker.resolve_target(payload(tool_input={"repo": "gitapex"}, tool_response={"number": 3}))
    assert "owner/repo" in str(excinfo.value)


@pytest.mark.parametrize("bad_input", [[], "x", 1, None])
def test_a_non_object_tool_input_does_not_raise_attributeerror(bad_input: Any) -> None:
    with pytest.raises(checker.VerificationError):
        checker.resolve_target({"tool_name": "mcp__github__create_pull_request", "tool_input": bad_input})


@pytest.mark.parametrize("bad_response", [[], "x", 1, {"content": 5}, {"content": [1, 2]}])
def test_a_non_object_tool_response_normalizes_to_empty(bad_response: Any) -> None:
    assert checker.response_payload(bad_response) == ({} if not isinstance(bad_response, dict) else bad_response)


# --- target resolution from the response URL (issue #908) -----------------
#
# The two constants below are the *observed* create-call responses recorded
# in issue #908's fact 1, copied verbatim rather than constructed here --
# that issue's own root cause (fact 7) is an extractor written against
# hypothesised envelopes that were never checked against a real one, so a
# regression suite built on invented fixtures would repeat it. Both were
# read off the live tool result in the session that filed #905: note that
# `id` is a string there, and that no `number` field exists at all.

_OBSERVED_CREATE_PR_RESPONSE = {"id": "4235739033", "url": "https://github.com/tvna/gitapex/pull/884"}
_OBSERVED_CREATE_ISSUE_RESPONSE = {"id": "5100051513", "url": "https://github.com/tvna/gitapex/issues/905"}


def test_number_comes_from_the_response_url_when_create_pull_request_carries_no_number_field() -> None:
    resolved = checker.resolve_target(payload(tool_response=_OBSERVED_CREATE_PR_RESPONSE))
    assert resolved == ("tvna", "gitapex", 884)


def test_number_comes_from_the_response_url_when_issue_write_create_carries_no_number_field() -> None:
    resolved = checker.resolve_target(
        payload(tool_name="mcp__github__issue_write", tool_response=_OBSERVED_CREATE_ISSUE_RESPONSE)
    )
    assert resolved == ("tvna", "gitapex", 905)


def test_the_internal_database_id_is_never_read_as_the_issue_number() -> None:
    """`id` and the artifact number are different values (5100051513 versus
    905, issue #908 fact 4); only the latter addresses the REST endpoint, so
    reading `id` would re-scan an unrelated artifact or 404."""
    for identifier in ("5100051513", 5100051513):
        resolved = checker.resolve_target(
            payload(tool_response={"id": identifier, "url": "https://github.com/tvna/gitapex/issues/905"})
        )
        assert resolved == ("tvna", "gitapex", 905)


def test_an_id_without_a_url_is_still_indeterminate() -> None:
    """The guard on the row above: `id` must not have been added to the
    number fields as a shortcut, which this payload would otherwise pass."""
    with pytest.raises(checker.VerificationError):
        checker.resolve_target(payload(tool_response={"id": "5100051513"}))


@pytest.mark.parametrize(
    ("url", "expected"),
    [
        ("https://github.com/tvna/gitapex/pull/884", 884),
        ("https://github.com/tvna/gitapex/issues/905", 905),
        # The REST spelling, in case a server version returns the API URL.
        ("https://api.github.com/repos/tvna/gitapex/pulls/884", 884),
        # Trailing path, query, and fragment must not swallow the number.
        ("https://github.com/tvna/gitapex/pull/884/files", 884),
        ("https://github.com/tvna/gitapex/issues/905#issuecomment-1", 905),
        ("https://github.com/tvna/gitapex/issues/905?foo=bar", 905),
        # A repository literally named "issues" must not shadow the tail.
        ("https://github.com/tvna/issues/issues/12", 12),
    ],
)
def test_a_url_tail_resolves_to_its_artifact_number(url: str, expected: int) -> None:
    assert checker.resolve_target(payload(tool_response={"url": url})) == ("tvna", "gitapex", expected)


def test_the_html_url_spelling_is_tolerated() -> None:
    """Same tolerance rationale as the alternate number-field spellings: a
    server-side rename should degrade to a still-working lookup."""
    resolved = checker.resolve_target(payload(tool_response={"html_url": "https://github.com/tvna/gitapex/issues/905"}))
    assert resolved == ("tvna", "gitapex", 905)


def test_a_url_number_is_read_through_the_mcp_content_envelope() -> None:
    resolved = checker.resolve_target(payload(tool_response={"content": json.dumps(_OBSERVED_CREATE_ISSUE_RESPONSE)}))
    assert resolved == ("tvna", "gitapex", 905)


def test_a_number_field_still_wins_over_the_url_tail() -> None:
    """The update paths resolve from tool_input today and must keep doing
    so: the submitted argument is the request's own target, and the URL
    fallback exists only for the create calls that carry no such field."""
    resolved = checker.resolve_target(
        payload(
            tool_name="mcp__github__update_pull_request",
            tool_input={"owner": "tvna", "repo": "gitapex", "pullNumber": 42},
            tool_response={"url": "https://github.com/tvna/gitapex/pull/884"},
        )
    )
    assert resolved == ("tvna", "gitapex", 42)


@pytest.mark.parametrize(
    "url",
    [
        "https://github.com/tvna/gitapex",
        "https://github.com/tvna/gitapex/issues/0",
        "https://github.com/tvna/gitapex/issues/latest",
        "https://github.com/tvna/gitapex/commit/9aed5ef",
        "not a url at all",
        "",
    ],
)
def test_an_unparseable_url_still_reports_indeterminate(url: str) -> None:
    """Issue #908's third criterion: the property that made this defect
    visible has to survive the fix -- a broader extractor must not become a
    guessier one."""
    with pytest.raises(checker.VerificationError):
        checker.resolve_target(payload(tool_response={"url": url}))


@pytest.mark.parametrize("bad_url", [1, None, [], {"nested": "x"}, True])
def test_a_non_string_url_does_not_raise(bad_url: Any) -> None:
    with pytest.raises(checker.VerificationError):
        checker.resolve_target(payload(tool_response={"url": bad_url}))


# --- evaluate() verdicts --------------------------------------------------


@pytest.mark.parametrize(
    "tool_name",
    [
        "Bash",
        "mcp__github__merge_pull_request",
        "mcp__github__issue_read",
        "",
    ],
)
def test_an_uncovered_tool_skips(tool_name: str) -> None:
    verdict, _ = checker.evaluate(payload(tool_name=tool_name), "tok", fetcher=fetcher_returning(""))
    assert verdict == "SKIP"


@pytest.mark.parametrize("bad_name", [None, 5, [], {}])
def test_a_non_string_tool_name_skips_without_raising(bad_name: Any) -> None:
    verdict, _ = checker.evaluate({"tool_name": bad_name}, "tok", fetcher=fetcher_returning(""))
    assert verdict == "SKIP"


@pytest.mark.parametrize(
    "tool_name",
    [
        "mcp__github__create_pull_request",
        "mcp__github__update_pull_request",
        "mcp__github__issue_write",
    ],
)
def test_every_covered_tool_is_scanned(tool_name: str) -> None:
    verdict, _ = checker.evaluate(
        payload(
            tool_name=tool_name,
            tool_input={"owner": "tvna", "repo": "gitapex", "number": 1},
        ),
        "tok",
        fetcher=fetcher_returning("clean ASCII body\n"),
    )
    assert verdict == "PASS"


@pytest.mark.parametrize(
    "failure_marker",
    [{"status": "error"}, {"is_error": True}, {"isError": True}],
)
def test_a_failed_write_skips_rather_than_reporting_unverified(failure_marker: dict[str, Any]) -> None:
    response = {"number": 5, **failure_marker}
    verdict, _ = checker.evaluate(payload(tool_response=response), "tok", fetcher=fetcher_returning(_LEAKED_BODY))
    assert verdict == "SKIP"


def test_a_successful_status_is_still_scanned() -> None:
    verdict, _ = checker.evaluate(
        payload(tool_response={"number": 5, "status": "success"}),
        "tok",
        fetcher=fetcher_returning("clean\n"),
    )
    assert verdict == "PASS"


def test_the_same_fixture_that_trips_the_pre_write_scan_trips_this_path() -> None:
    """Issue #878's acceptance criterion: the post-write path must trip on
    the same content the pre-write scan trips on. Asserted against the
    shipped scanner itself, not a stub, so the two paths cannot drift."""
    scanner = checker.load_provenance_scanner()
    assert scanner.scan(_LEAKED_BODY), "fixture must trip the pre-write scan for this test to mean anything"

    verdict, message = checker.evaluate(
        payload(tool_response={"number": 5}), "tok", fetcher=fetcher_returning(_LEAKED_BODY)
    )
    assert verdict == "FLAGGED"
    assert "claude-example-model" in message
    assert "STORED body" in message


def test_a_non_ascii_only_body_is_flagged_too() -> None:
    verdict, message = checker.evaluate(
        payload(tool_response={"number": 5}),
        "tok",
        fetcher=fetcher_returning("Closes #878 \u2014 done\n"),
    )
    assert verdict == "FLAGGED"
    assert "U+2014" in message


def test_the_draft_is_never_the_scan_input() -> None:
    """The submitted draft is clean and the stored body is not. A check
    that scanned `tool_input.body` would pass here; only one that scans
    the re-fetched body flags it."""
    verdict, _ = checker.evaluate(
        payload(
            tool_input={"owner": "tvna", "repo": "gitapex", "body": "totally clean draft"},
            tool_response={"number": 5},
        ),
        "tok",
        fetcher=fetcher_returning(_LEAKED_BODY),
    )
    assert verdict == "FLAGGED"


def test_a_missing_token_is_indeterminate_not_a_clean_pass() -> None:
    verdict, message = checker.evaluate(payload(tool_response={"number": 5}), None)
    assert verdict == "INDETERMINATE"
    assert "GH_TOKEN" in message


def test_an_api_failure_is_indeterminate_not_a_clean_pass() -> None:
    def failing_fetcher(owner: str, repo: str, number: int, token: str) -> dict[str, str]:
        raise pr_issue_checker.GitHubApiError("fetch-failed: HTTP 503")

    verdict, message = checker.evaluate(payload(tool_response={"number": 5}), "tok", fetcher=failing_fetcher)
    assert verdict == "INDETERMINATE"
    assert "503" in message


def test_a_non_github_api_error_is_indeterminate_not_a_traceback() -> None:
    """The shared fetch path parses its response with a bare json.loads, so
    a 2xx carrying a proxy interstitial raises JSONDecodeError -- a
    ValueError, not a GitHubApiError. Before this was caught it escaped
    every handler and surfaced through the wrapper as a raw traceback in
    the report's own reason field."""

    def decoding_fetcher(owner: str, repo: str, number: int, token: str) -> dict[str, str]:
        raise json.JSONDecodeError("Expecting value", "<html>not json</html>", 0)

    verdict, message = checker.evaluate(payload(tool_response={"number": 5}), "tok", fetcher=decoding_fetcher)
    assert verdict == "INDETERMINATE"
    assert "JSONDecodeError" in message
    assert "Traceback" not in message


def test_an_unexpected_error_class_is_also_indeterminate() -> None:
    def exploding_fetcher(owner: str, repo: str, number: int, token: str) -> dict[str, str]:
        raise RuntimeError("something nobody anticipated")

    verdict, message = checker.evaluate(payload(tool_response={"number": 5}), "tok", fetcher=exploding_fetcher)
    assert verdict == "INDETERMINATE"
    assert "RuntimeError" in message


@pytest.mark.parametrize("degenerate", [{}, {"body": ""}, {"body": "clean", "state": ""}, {"state": None}])
def test_a_response_that_is_not_an_issue_is_indeterminate_not_a_clean_pass(degenerate: dict[str, Any]) -> None:
    """A 2xx with an empty response body normalizes to {} in the shared
    fetch path. Scanning that as an empty string reported PASS -- the one
    place an inability to verify rendered as 'clean'."""

    def degenerate_fetcher(owner: str, repo: str, number: int, token: str) -> dict[str, Any]:
        return degenerate

    verdict, message = checker.evaluate(payload(tool_response={"number": 5}), "tok", fetcher=degenerate_fetcher)
    assert verdict == "INDETERMINATE"
    assert "no issue state" in message


def test_a_real_looking_response_still_passes() -> None:
    """The guard above must not turn every clean artifact into
    INDETERMINATE: a response carrying a real state scans normally."""
    verdict, _ = checker.evaluate(
        payload(tool_response={"number": 5}), "tok", fetcher=fetcher_returning("clean ASCII body")
    )
    assert verdict == "PASS"


def test_an_unresolvable_number_is_indeterminate_not_a_clean_pass() -> None:
    verdict, message = checker.evaluate(payload(tool_response={}), "tok", fetcher=fetcher_returning(""))
    assert verdict == "INDETERMINATE"
    assert "number" in message


def test_a_null_body_scans_as_empty_rather_than_crashing() -> None:
    def null_body_fetcher(owner: str, repo: str, number: int, token: str) -> dict[str, Any]:
        return {"body": None, "state": "open"}

    verdict, _ = checker.evaluate(payload(tool_response={"number": 5}), "tok", fetcher=null_body_fetcher)
    assert verdict == "PASS"


def test_hit_reporting_is_capped_but_the_count_is_not() -> None:
    body = "\n".join("x\u2014" for _ in range(50))
    verdict, message = checker.evaluate(payload(tool_response={"number": 5}), "tok", fetcher=fetcher_returning(body))
    assert verdict == "FLAGGED"
    assert "50 non-ASCII character(s)" in message
    assert "and 30 more" in message


# --- main() ---------------------------------------------------------------


def test_main_reports_indeterminate_on_a_non_object_payload(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.setattr("sys.stdin", _StringStdin("[1, 2, 3]"))
    assert checker.main([]) == 1
    assert "INDETERMINATE" in capsys.readouterr().err


def test_main_reports_indeterminate_on_invalid_json(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.setattr("sys.stdin", _StringStdin("not json at all"))
    assert checker.main([]) == 1
    assert "INDETERMINATE" in capsys.readouterr().err


def test_main_skips_an_empty_payload(monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]) -> None:
    monkeypatch.setattr("sys.stdin", _StringStdin(""))
    assert checker.main([]) == 0
    assert "SKIP" in capsys.readouterr().out


def test_main_reports_a_missing_payload_file(capsys: pytest.CaptureFixture[str]) -> None:
    assert checker.main(["--payload", str(REPO_ROOT / "no-such-payload.json")]) == 1
    assert "not found" in capsys.readouterr().err


def test_main_reads_a_payload_file(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    path = tmp_path / "payload.json"
    path.write_text(json.dumps({"tool_name": "Bash"}), encoding="utf-8")
    assert checker.main(["--payload", str(path)]) == 0
    assert "SKIP" in capsys.readouterr().out


def test_a_spec_that_will_not_load_is_indeterminate(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """importlib can return a spec with no loader for a path it recognizes
    but cannot execute. That must reach the INDETERMINATE path, not raise
    an AttributeError on `spec.loader.exec_module`."""
    target = tmp_path / "loadable.py"
    target.write_text("x = 1\n", encoding="utf-8")
    monkeypatch.setattr(checker.importlib.util, "spec_from_file_location", lambda *a, **k: None)
    with pytest.raises(checker.VerificationError) as excinfo:
        checker.load_provenance_scanner(target)
    assert "could not be loaded" in str(excinfo.value)


def test_provenance_hit_reporting_is_capped_but_the_count_is_not() -> None:
    """The ASCII half's cap is covered above; this covers the provenance
    half's own truncation branch, which is a separate code path."""
    body = "\n".join(f"Generated by tool-{index}" for index in range(25))
    verdict, message = checker.evaluate(payload(tool_response={"number": 5}), "tok", fetcher=fetcher_returning(body))
    assert verdict == "FLAGGED"
    assert "25 candidate provenance marker(s)" in message
    assert "and 5 more" in message


def test_the_default_fetcher_delegates_to_the_shared_hook_helper(monkeypatch: pytest.MonkeyPatch) -> None:
    """evaluate()'s default fetcher must be the already-tested
    hooks/gitapex_check_pr_issue_acm_disclosure.py helper, not a second
    copy of the retry/backoff logic."""
    seen: dict[str, object] = {}

    def fake_fetch_issue(owner: str, repo: str, number: int, token: str) -> dict[str, str]:
        seen.update({"owner": owner, "repo": repo, "number": number, "token": token})
        return {"body": "clean", "state": "open"}

    monkeypatch.setattr(pr_issue_checker, "fetch_issue", fake_fetch_issue)
    verdict, _ = checker.evaluate(payload(tool_response={"number": 5}), "tok")
    assert verdict == "PASS"
    assert seen == {"owner": "tvna", "repo": "gitapex", "number": 5, "token": "tok"}


def test_main_reports_a_non_utf8_payload_file(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    path = tmp_path / "payload.json"
    path.write_bytes(b'{"tool_name": "\xff\xfe"}')
    assert checker.main(["--payload", str(path)]) == 1
    assert "not valid UTF-8" in capsys.readouterr().err


def test_main_exits_one_and_reports_on_stderr_for_an_unverifiable_target(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    """A covered tool whose target cannot be resolved never reaches the
    network, so this exercises main()'s own non-zero exit path without a
    fetch."""
    monkeypatch.setattr(
        "sys.stdin",
        _StringStdin(json.dumps({"tool_name": "mcp__github__create_pull_request", "tool_input": {}})),
    )
    assert checker.main([]) == 1
    assert "INDETERMINATE" in capsys.readouterr().err


class _StringStdin:
    def __init__(self, data: str) -> None:
        self._data = data

    def read(self) -> str:
        return self._data
