"""Tests for flake.nix's devShell hook-install shellHook (issue #890).

This shellHook was hand-verified four times across a growing matrix of git
layouts while #890's review rounds found successive blind spots in it: a
`[ -d .git ]` guard that skipped silently from a subdirectory and inside a
linked worktree, a hard-coded `.git/hooks` that is the wrong path in both, an
install-from-worktree that corrupted the main checkout's shared shims, and an
`-x` check that passes on a shim which cannot actually run. Four rounds of
manual re-verification is exactly the "agent memory standing in for an absent
gate" CLAUDE.md section 3 forbids, so the checks are written down here instead.

The shellHook body is extracted from flake.nix rather than duplicated, so these
tests fail if the real text stops matching them. Same shape as
tests/test_gitapex_session_start_hook_shell.py, which tests a shell hook
directly rather than a Python entry point.

Nothing here touches the working checkout: every case fabricates its own shim
files under tmp_path, and the one integration test clones into tmp_path. That
isolation is deliberate -- an earlier hand-run of the worktree case against the
real repository rewrote its shims and broke `git push` until they were
reinstalled.
"""

from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path

import pytest

_FLAKE = Path(__file__).resolve().parent.parent / "flake.nix"
_SHELL_HOOK_RE = re.compile(r"shellHook = ''\n(?P<body>.*?)\n\s*'';", re.DOTALL)

# A prek shim's shape, reduced to the two lines the shellHook reasons about.
# Mirrors what `prek install` generates (verified against the real shim).
_SHIM_TEMPLATE = """\
#!/bin/sh
# File generated by prek: https://github.com/j178/prek
PREK="{target}"
if [ ! -x "$PREK" ]; then
    PREK="prek"
fi
exec "$PREK" hook-impl --hook-type=pre-push -- "$@"
"""


def shell_hook_body() -> str:
    """Return flake.nix's devShell shellHook body verbatim."""
    match = _SHELL_HOOK_RE.search(_FLAKE.read_text(encoding="utf-8"))
    assert match is not None, "could not locate the shellHook body in flake.nix"
    return match.group("body")


def shell_hook_code() -> str:
    """Return the shellHook body with comment-only lines dropped.

    The shape assertions below are about what the hook *executes*. Matching raw
    text would also match the explanatory comments -- which name the very
    anti-patterns being banned -- so a future comment edit would fail these
    tests for the wrong reason. A gate that fails spuriously gets disabled.
    """
    return "\n".join(line for line in shell_hook_body().splitlines() if not line.lstrip().startswith("#"))


def write_shim(path: Path, target: str, *, executable: bool = True) -> Path:
    path.write_text(_SHIM_TEMPLATE.format(target=target), encoding="utf-8")
    path.chmod(0o755 if executable else 0o644)
    return path


def run_predicate(shim: Path, *, prek_on_path: bool) -> bool:
    """Return whether the shellHook's own predicate calls `shim` broken.

    Sources the function straight out of flake.nix, so a rewrite that drops the
    target-validity check fails these tests rather than passing quietly.
    """
    script = f'{shell_hook_body()}\nprek_shim_broken "{shim}" && echo BROKEN || echo OK\n'
    env = {"PATH": "/usr/bin:/bin"}
    if prek_on_path:
        # A directory containing a real `prek`, so the shim's PATH fallback resolves.
        fake_bin = shim.parent / "fakebin"
        fake_bin.mkdir(exist_ok=True)
        (fake_bin / "prek").write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
        (fake_bin / "prek").chmod(0o755)
        env["PATH"] = f"{fake_bin}:{env['PATH']}"
    completed = subprocess.run(("bash", "-c", script), capture_output=True, text=True, env=env, check=False)
    return "BROKEN" in completed.stdout


def test_a_shim_whose_own_target_resolves_is_not_broken(tmp_path: Path) -> None:
    target = tmp_path / "prek"
    target.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    target.chmod(0o755)
    shim = write_shim(tmp_path / "pre-push", str(target))
    assert run_predicate(shim, prek_on_path=False) is False


def test_an_executable_shim_with_a_dangling_target_and_no_fallback_is_broken(tmp_path: Path) -> None:
    # The regression that four rounds of `-x` checking missed: the shim is
    # present and executable, and still dies at `exec` with "prek: not found".
    shim = write_shim(tmp_path / "pre-push", "/nonexistent/removed-worktree/.venv/bin/prek")
    assert run_predicate(shim, prek_on_path=False) is True


def test_a_dangling_target_is_tolerated_when_prek_is_really_on_path(tmp_path: Path) -> None:
    # The shim's own fallback branch makes it work again, so warning would be
    # a false positive.
    shim = write_shim(tmp_path / "pre-push", "/nonexistent/gone/.venv/bin/prek")
    assert run_predicate(shim, prek_on_path=True) is False


def test_a_non_executable_shim_is_broken(tmp_path: Path) -> None:
    target = tmp_path / "prek"
    target.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    target.chmod(0o755)
    shim = write_shim(tmp_path / "pre-push", str(target), executable=False)
    assert run_predicate(shim, prek_on_path=False) is True


def test_a_missing_shim_is_broken(tmp_path: Path) -> None:
    assert run_predicate(tmp_path / "absent", prek_on_path=False) is True


def test_the_shell_hook_uses_the_predicate_rather_than_a_bare_executable_test() -> None:
    code = shell_hook_code()
    assert "prek_shim_broken()" in code, "the target-validity predicate must stay defined"
    # Every hook-state decision must go through the predicate. A bare
    # `-x "$hooks/...` would reintroduce the stale-shim blind spot.
    assert '-x "$hooks/' not in code
    assert code.count("prek_shim_broken ") >= 3


def test_the_shell_hook_discovers_the_repository_instead_of_testing_for_a_git_directory() -> None:
    code = shell_hook_code()
    # `[ -d .git ]` is false from a subdirectory and in a linked worktree.
    assert "[ -d .git ]" not in code
    assert "git rev-parse --show-toplevel" in code
    # A literal .git/hooks ignores core.hooksPath and is wrong in a worktree.
    assert "git rev-parse --git-path hooks" in code
    assert ".git/hooks" not in code


def test_the_shell_hook_distinguishes_a_linked_worktree_before_installing() -> None:
    code = shell_hook_code()
    assert "--git-common-dir" in code, "a linked worktree must not install shared hooks"
    install_index = code.index("prek install --quiet")
    common_dir_index = code.index("--git-common-dir")
    assert common_dir_index < install_index, "the worktree check must gate the install, not follow it"


@pytest.mark.slow
@pytest.mark.skipif(shutil.which("git") is None, reason="needs git")
def test_a_linked_worktree_warns_without_installing_over_the_shared_shims(tmp_path: Path) -> None:
    """End-to-end: a worktree with a stale shared shim warns and writes nothing.

    Clones into tmp_path so the working checkout is never the subject.
    """
    origin = Path(__file__).resolve().parent.parent
    clone = tmp_path / "clone"
    subprocess.run(
        ("git", "clone", "--quiet", "--no-hardlinks", str(origin), str(clone)),
        check=True,
        capture_output=True,
    )
    hooks = clone / ".git" / "hooks"
    for name in ("pre-commit", "pre-push"):
        write_shim(hooks / name, "/nonexistent/removed-worktree/.venv/bin/prek")
    before = {name: (hooks / name).read_bytes() for name in ("pre-commit", "pre-push")}

    worktree = tmp_path / "wt"
    subprocess.run(
        ("git", "-C", str(clone), "worktree", "add", "--quiet", "--detach", str(worktree), "HEAD"),
        check=True,
        capture_output=True,
    )

    completed = subprocess.run(
        ("bash", "-c", shell_hook_body()),
        cwd=worktree,
        capture_output=True,
        text=True,
        env={"PATH": "/usr/bin:/bin"},
        check=False,
    )

    assert "WARNING" in completed.stderr
    assert "linked worktree" in completed.stderr
    assert "main checkout" in completed.stderr
    # The whole point: it must not rewrite hooks it does not own.
    assert {name: (hooks / name).read_bytes() for name in ("pre-commit", "pre-push")} == before


@pytest.mark.slow
def test_outside_a_repository_the_shell_hook_is_a_silent_no_op(tmp_path: Path) -> None:
    # Preserves what the `[ -d .git ]` guard was originally for (issue #725):
    # `nix develop` outside a checkout must not error.
    completed = subprocess.run(
        ("bash", "-c", shell_hook_body()),
        cwd=tmp_path,
        capture_output=True,
        text=True,
        env={"PATH": "/usr/bin:/bin"},
        check=False,
    )
    assert completed.stdout == ""
    assert completed.stderr == ""
