"""Direct-import, fetcher-injection unit suite for
hooks/gitapex_check_post_write_provenance.py (issue #878).

No test in this file makes a real network call -- the network layer is
exercised through an injected `fetcher`, the same injection style
tests/test_gitapex_check_pr_issue_acm_disclosure.py uses for its own
`opener`. `hooks` is on pyproject.toml's `pythonpath`, so this module
imports as a plain top-level module rather than via importlib.util.

Subprocess-level `.sh`-wrapper tests live in
hooks/test_gitapex_check_post_write_provenance_shell.py instead -- see
that file's own docstring for why the split, and for the pytest basename
collision the `_shell` suffix avoids.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import gitapex_check_post_write_provenance as checker
import gitapex_check_pr_issue_acm_disclosure as pr_issue_checker
import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]

_LEAKED_BODY = (
    "Refs #878\n\nGenerated by claude-example-model during session https://claude.ai/code/session_01Example99"
)


def fetcher_returning(body: str) -> Any:
    def fetcher(owner: str, repo: str, number: int, token: str) -> dict[str, str]:
        return {"body": body, "state": "open"}

    return fetcher


def payload(
    *,
    tool_name: str = "mcp__github__create_pull_request",
    tool_input: dict[str, Any] | None = None,
    tool_response: Any = None,
) -> dict[str, Any]:
    built: dict[str, Any] = {"tool_name": tool_name}
    built["tool_input"] = {"owner": "tvna", "repo": "gitapex"} if tool_input is None else tool_input
    if tool_response is not None:
        built["tool_response"] = tool_response
    return built


# --- scanner loading ------------------------------------------------------


def test_default_scanner_path_resolves_to_the_shipped_scanner() -> None:
    """The relative path this hook resolves must really exist in the
    repository tree -- a hook that silently cannot find its own scanner
    would report INDETERMINATE forever, and no unit test injecting a
    scanner_path would notice."""
    module = checker.load_provenance_scanner()
    assert callable(module.scan)


def test_missing_scanner_is_indeterminate_not_a_clean_pass(tmp_path: Path) -> None:
    with pytest.raises(checker.VerificationError) as excinfo:
        checker.load_provenance_scanner(tmp_path / "absent.py")
    assert "not found" in str(excinfo.value)


def test_unimportable_scanner_is_indeterminate_not_a_clean_pass(tmp_path: Path) -> None:
    broken = tmp_path / "broken.py"
    broken.write_text("raise RuntimeError('boom')\n", encoding="utf-8")
    with pytest.raises(checker.VerificationError) as excinfo:
        checker.load_provenance_scanner(broken)
    assert "failed to import" in str(excinfo.value)


# --- ASCII scan (outward-artifact-preflight checklist item 2) --------------


def test_an_importable_module_without_scan_is_indeterminate(tmp_path: Path) -> None:
    """A file can sit at the expected path, import cleanly, and still not be
    the scanner. Without the contract check that mismatch surfaced as an
    AttributeError from scan_body(), forwarded as a raw traceback."""
    impostor = tmp_path / "impostor.py"
    impostor.write_text("VALUE = 1\n", encoding="utf-8")
    with pytest.raises(checker.VerificationError) as excinfo:
        checker.load_provenance_scanner(impostor)
    assert "no callable scan()" in str(excinfo.value)


def test_a_non_callable_scan_attribute_is_also_rejected(tmp_path: Path) -> None:
    impostor = tmp_path / "impostor.py"
    impostor.write_text("scan = 'not a function'\n", encoding="utf-8")
    with pytest.raises(checker.VerificationError):
        checker.load_provenance_scanner(impostor)


def test_pure_ascii_body_has_no_ascii_hits() -> None:
    assert checker.scan_non_ascii("Closes #878\n\nPlain ASCII body.\t(tabbed)\r\n") == []


def test_em_dash_is_reported_by_codepoint_not_echoed() -> None:
    hits = checker.scan_non_ascii("a \u2014 b")
    assert hits == [(1, 3, "U+2014 EM DASH")]
    assert "\u2014" not in hits[0][2]


def test_every_occurrence_is_reported_with_its_own_line_and_column() -> None:
    hits = checker.scan_non_ascii("x\u00e9\nyy\u00e9")
    assert [(line, column) for line, column, _ in hits] == [(1, 2), (2, 3)]


@pytest.mark.parametrize(
    ("body", "expected"),
    [
        ("\u2028", "U+2028 LINE SEPARATOR"),
        ("\u2029", "U+2029 PARAGRAPH SEPARATOR"),
        ("\u0085", "U+0085 unnamed character"),
        ("a\u000bb", "U+000B unnamed character"),
        ("a\u000cb", "U+000C unnamed character"),
        ("a\u001eb", "U+001E unnamed character"),
    ],
)
def test_a_character_str_splitlines_would_swallow_is_still_reported(body: str, expected: str) -> None:
    """str.splitlines() splits on every one of these, consuming exactly the
    characters this scan exists to report -- a body of a single U+2028
    scanned clean before this regression was closed."""
    hits = checker.scan_non_ascii(body)
    assert [label for _, _, label in hits] == [expected]


def test_a_crlf_body_reports_nothing_extra_after_the_split_change() -> None:
    """Splitting on "\n" alone leaves a bare \r at each line's end; it must
    stay an allowed character, not become a new false positive."""
    assert checker.scan_non_ascii("line one\r\nline two\r\n") == []


def test_unnamed_codepoint_does_not_crash_the_scan() -> None:
    """A codepoint with no formal Unicode name (an unassigned/private-use
    character) must still report, not raise -- unicodedata.name() raises
    ValueError without the default argument this scan passes."""
    hits = checker.scan_non_ascii("\ue000")
    assert hits == [(1, 1, "U+E000 unnamed character")]


# --- CONTRIBUTING.md ratified-trailer section quoting (issue #1446) -------


def test_extract_markdown_section_returns_body_up_to_next_heading() -> None:
    text = "# Title\n\n## first\n\nfirst body line one\nfirst body line two\n\n## second\n\nsecond body\n"
    assert checker.extract_markdown_section(text, "## first") == "first body line one\nfirst body line two"


def test_extract_markdown_section_runs_to_end_of_file_when_no_next_heading() -> None:
    text = "## only\n\nlast body line\nmore text\n"
    assert checker.extract_markdown_section(text, "## only") == "last body line\nmore text"


def test_extract_markdown_section_returns_none_when_heading_absent() -> None:
    assert checker.extract_markdown_section("## other\n\nbody\n", "## missing") is None


def test_extract_markdown_section_requires_an_exact_line_match() -> None:
    """A heading that only appears as a substring of a longer line (not on
    its own line) must not match -- otherwise a coincidental prose mention
    of the heading text could be read as the section itself."""
    text = "prefix ## first suffix\n\nbody\n"
    assert checker.extract_markdown_section(text, "## first") is None


def test_extract_markdown_section_heading_with_trailing_whitespace_does_not_match() -> None:
    """Defeat case (issue #1446 step 8 adversarial review): a heading line
    carrying trailing whitespace must NOT match the clean heading constant
    -- `lines.index(heading)` requires byte-for-byte equality, by design
    (see this function's own docstring), so a stray trailing space
    silently degrades extraction to None rather than matching loosely.
    Confirmed today's real CONTRIBUTING.md heading carries no such
    whitespace, so this is a live non-issue, not a live bug."""
    text = "# Title\n\n## first   \n\nbody\n\n## second\n"
    assert checker.extract_markdown_section(text, "## first") is None


def test_extract_markdown_section_duplicate_heading_returns_first_occurrence() -> None:
    """Defeat case: when a heading text appears twice, `list.index()`
    picks the first occurrence deterministically. Pinned as the intended
    behavior (not a defect) -- a well-formed CONTRIBUTING.md has no
    duplicate headings, and "first wins" is a reasonable, deterministic
    default for the degenerate case where one does."""
    text = "## dup\n\nfirst body\n\n## other\n\n## dup\n\nsecond body\n"
    assert checker.extract_markdown_section(text, "## dup") == "first body"


def test_extract_markdown_section_final_line_at_eof_is_not_truncated() -> None:
    """Defeat case: the last section in a file, with no trailing newline
    at all, must not off-by-one drop its final line."""
    text = "## only\n\nlast body line"
    assert checker.extract_markdown_section(text, "## only") == "last body line"


def test_default_contributing_path_extracts_the_real_ratified_section() -> None:
    """The relative path this hook resolves for CONTRIBUTING.md must
    really find the ratified section in this repository's own checkout --
    a hook that silently could not locate its own CONTRIBUTING.md would
    fall back to the named-section message forever, and no unit test
    injecting a contributing_path would notice."""
    text = checker.ratified_trailer_disclosure_text()
    assert "agreed, disclosed convention" in text
    assert "issues/687" in text


def test_ratified_trailer_disclosure_falls_back_when_contributing_md_is_missing(tmp_path: Path) -> None:
    """hooks/ is also shipped standalone to plugin-distributed consumer
    checkouts that may not carry CONTRIBUTING.md at all
    (docs/repository-layout.md) -- a missing file must degrade to naming
    the section, never crash and never silently drop the judgment-call
    framing this text feeds into."""
    text = checker.ratified_trailer_disclosure_text(tmp_path / "absent-CONTRIBUTING.md")
    assert "outward-artifact-preflight: PR-body trailer disclosure" in text
    assert "could not be located" in text


def test_ratified_trailer_disclosure_falls_back_when_heading_is_absent(tmp_path: Path) -> None:
    """A CONTRIBUTING.md that exists but whose section has since moved or
    been renamed must also degrade to the named-section fallback, not
    raise and not quote unrelated content."""
    contributing = tmp_path / "CONTRIBUTING.md"
    contributing.write_text("## some other section\n\nunrelated body\n", encoding="utf-8")
    text = checker.ratified_trailer_disclosure_text(contributing)
    assert "outward-artifact-preflight: PR-body trailer disclosure" in text
    assert "could not be located" in text
    assert "unrelated body" not in text


# --- target resolution ----------------------------------------------------


def test_number_comes_from_tool_input_on_an_update() -> None:
    resolved = checker.resolve_target(
        payload(
            tool_name="mcp__github__update_pull_request",
            tool_input={"owner": "tvna", "repo": "gitapex", "pullNumber": 42},
        )
    )
    assert resolved == ("tvna", "gitapex", 42)


def test_number_comes_from_the_response_on_a_create() -> None:
    resolved = checker.resolve_target(payload(tool_response={"number": 7}))
    assert resolved == ("tvna", "gitapex", 7)


def test_number_is_read_from_an_mcp_content_string_envelope() -> None:
    resolved = checker.resolve_target(payload(tool_response={"content": json.dumps({"number": 9})}))
    assert resolved == ("tvna", "gitapex", 9)


def test_number_is_read_from_an_mcp_text_block_list_envelope() -> None:
    resolved = checker.resolve_target(
        payload(tool_response={"content": [{"type": "text", "text": json.dumps({"number": 11})}]})
    )
    assert resolved == ("tvna", "gitapex", 11)


def test_a_non_json_text_block_falls_through_to_the_next_block() -> None:
    resolved = checker.resolve_target(
        payload(
            tool_response={
                "content": [
                    {"type": "text", "text": "not json at all"},
                    {"type": "text", "text": json.dumps({"number": 13})},
                ]
            }
        )
    )
    assert resolved == ("tvna", "gitapex", 13)


def test_a_string_number_is_accepted() -> None:
    resolved = checker.resolve_target(payload(tool_response={"number": "17"}))
    assert resolved == ("tvna", "gitapex", 17)


def test_a_boolean_number_is_rejected_not_read_as_pr_one() -> None:
    """isinstance(True, int) is True in Python, so an unguarded read would
    resolve {"number": true} to PR #1 and re-scan an unrelated artifact."""
    with pytest.raises(checker.VerificationError):
        checker.resolve_target(payload(tool_response={"number": True}))


@pytest.mark.parametrize("bad", [0, -3, "0", "abc", None, 1.5])
def test_an_implausible_number_is_rejected(bad: Any) -> None:
    with pytest.raises(checker.VerificationError):
        checker.resolve_target(payload(tool_response={"number": bad}))


def test_a_missing_owner_is_verification_error() -> None:
    with pytest.raises(checker.VerificationError) as excinfo:
        checker.resolve_target(payload(tool_input={"repo": "gitapex"}, tool_response={"number": 3}))
    assert "owner/repo" in str(excinfo.value)


@pytest.mark.parametrize("bad_input", [[], "x", 1, None])
def test_a_non_object_tool_input_does_not_raise_attributeerror(bad_input: Any) -> None:
    with pytest.raises(checker.VerificationError):
        checker.resolve_target({"tool_name": "mcp__github__create_pull_request", "tool_input": bad_input})


@pytest.mark.parametrize("bad_response", [[], "x", 1, {"content": 5}, {"content": [1, 2]}])
def test_a_non_object_tool_response_normalizes_to_empty(bad_response: Any) -> None:
    assert checker.response_payload(bad_response) == ({} if not isinstance(bad_response, dict) else bad_response)


# --- target resolution from the response URL (issue #908) -----------------
#
# Every fixture below is an *observed* payload, copied verbatim rather than
# constructed here -- issue #908's own root cause (fact 7) is an extractor
# written against hypothesised envelopes that were never checked against a
# real one, so a regression suite built on invented fixtures would repeat
# it. Two observation points, both live:
#
# - The two objects below are the create-call responses issue #908's fact 1
#   records, read off the tool result in the session that filed #905. Note
#   that `id` is a string there, and that no `number` field exists at all.
# - _OBSERVED_POSTTOOLUSE_TOOL_RESPONSE is the whole `tool_response` value
#   as the hook harness actually delivers it, captured from a live
#   PostToolUse firing of mcp__github__update_pull_request on PR #909. It
#   is a *bare* MCP text-block list, not an object and not the
#   {"content": [...]} envelope this module's first version hypothesised --
#   which is why #908's first fix still reported INDETERMINATE on the
#   create path even with URL parsing in place: _coerce_mapping normalizes
#   a list to {}, so the `url` was unreachable.

_OBSERVED_CREATE_PR_RESPONSE = {"id": "4235739033", "url": "https://github.com/tvna/gitapex/pull/884"}
_OBSERVED_CREATE_ISSUE_RESPONSE = {"id": "5100051513", "url": "https://github.com/tvna/gitapex/issues/905"}
_OBSERVED_POSTTOOLUSE_TOOL_RESPONSE = [
    {"type": "text", "text": '{"id":"4236847118","url":"https://github.com/tvna/gitapex/pull/909"}'}
]


def test_the_observed_posttooluse_envelope_is_a_bare_text_block_list() -> None:
    """The captured payload's own shape, asserted so a future edit cannot
    quietly redefine what "observed" means here."""
    assert isinstance(_OBSERVED_POSTTOOLUSE_TOOL_RESPONSE, list)
    assert checker.response_payload(_OBSERVED_POSTTOOLUSE_TOOL_RESPONSE) == {
        "id": "4236847118",
        "url": "https://github.com/tvna/gitapex/pull/909",
    }


def test_the_observed_posttooluse_envelope_resolves_on_the_create_path() -> None:
    """The create path carries no number in tool_input, so this payload is
    the whole resolution chain: bare list -> text block -> JSON -> url ->
    number. It raised VerificationError before both halves of #908's fix."""
    resolved = checker.resolve_target(
        payload(tool_response=_OBSERVED_POSTTOOLUSE_TOOL_RESPONSE),
    )
    assert resolved == ("tvna", "gitapex", 909)


def test_a_bare_text_block_list_carrying_no_json_still_normalizes_to_empty() -> None:
    assert checker.response_payload([{"type": "text", "text": "not json"}]) == {}
    assert checker.response_payload([]) == {}
    assert checker.response_payload(["plain string", 7]) == {}


def test_number_comes_from_the_response_url_when_create_pull_request_carries_no_number_field() -> None:
    resolved = checker.resolve_target(payload(tool_response=_OBSERVED_CREATE_PR_RESPONSE))
    assert resolved == ("tvna", "gitapex", 884)


def test_number_comes_from_the_response_url_when_issue_write_create_carries_no_number_field() -> None:
    resolved = checker.resolve_target(
        payload(tool_name="mcp__github__issue_write", tool_response=_OBSERVED_CREATE_ISSUE_RESPONSE)
    )
    assert resolved == ("tvna", "gitapex", 905)


def test_the_internal_database_id_is_never_read_as_the_issue_number() -> None:
    """`id` and the artifact number are different values (5100051513 versus
    905, issue #908 fact 4); only the latter addresses the REST endpoint, so
    reading `id` would re-scan an unrelated artifact or 404."""
    for identifier in ("5100051513", 5100051513):
        resolved = checker.resolve_target(
            payload(tool_response={"id": identifier, "url": "https://github.com/tvna/gitapex/issues/905"})
        )
        assert resolved == ("tvna", "gitapex", 905)


def test_an_id_without_a_url_is_still_indeterminate() -> None:
    """The guard on the row above: `id` must not have been added to the
    number fields as a shortcut, which this payload would otherwise pass."""
    with pytest.raises(checker.VerificationError):
        checker.resolve_target(payload(tool_response={"id": "5100051513"}))


@pytest.mark.parametrize(
    ("url", "expected"),
    [
        ("https://github.com/tvna/gitapex/pull/884", 884),
        ("https://github.com/tvna/gitapex/issues/905", 905),
        # The REST spelling, in case a server version returns the API URL.
        ("https://api.github.com/repos/tvna/gitapex/pulls/884", 884),
        # Trailing path, query, and fragment must not swallow the number.
        ("https://github.com/tvna/gitapex/pull/884/files", 884),
        ("https://github.com/tvna/gitapex/issues/905#issuecomment-1", 905),
        ("https://github.com/tvna/gitapex/issues/905?foo=bar", 905),
        # A repository literally named "issues" must not shadow the tail.
        ("https://github.com/tvna/issues/issues/12", 12),
    ],
)
def test_a_url_tail_resolves_to_its_artifact_number(url: str, expected: int) -> None:
    assert checker.resolve_target(payload(tool_response={"url": url})) == ("tvna", "gitapex", expected)


def test_the_html_url_spelling_is_tolerated() -> None:
    """Same tolerance rationale as the alternate number-field spellings: a
    server-side rename should degrade to a still-working lookup."""
    resolved = checker.resolve_target(payload(tool_response={"html_url": "https://github.com/tvna/gitapex/issues/905"}))
    assert resolved == ("tvna", "gitapex", 905)


def test_a_url_number_is_read_through_the_mcp_content_envelope() -> None:
    resolved = checker.resolve_target(payload(tool_response={"content": json.dumps(_OBSERVED_CREATE_ISSUE_RESPONSE)}))
    assert resolved == ("tvna", "gitapex", 905)


def test_a_number_field_still_wins_over_the_url_tail() -> None:
    """The update paths resolve from tool_input today and must keep doing
    so: the submitted argument is the request's own target, and the URL
    fallback exists only for the create calls that carry no such field."""
    resolved = checker.resolve_target(
        payload(
            tool_name="mcp__github__update_pull_request",
            tool_input={"owner": "tvna", "repo": "gitapex", "pullNumber": 42},
            tool_response={"url": "https://github.com/tvna/gitapex/pull/884"},
        )
    )
    assert resolved == ("tvna", "gitapex", 42)


@pytest.mark.parametrize(
    "url",
    [
        "https://github.com/tvna/gitapex",
        "https://github.com/tvna/gitapex/issues/0",
        "https://github.com/tvna/gitapex/issues/latest",
        "https://github.com/tvna/gitapex/commit/9aed5ef",
        "not a url at all",
        "",
    ],
)
def test_an_unparseable_url_still_reports_indeterminate(url: str) -> None:
    """Issue #908's third criterion: the property that made this defect
    visible has to survive the fix -- a broader extractor must not become a
    guessier one."""
    with pytest.raises(checker.VerificationError):
        checker.resolve_target(payload(tool_response={"url": url}))


@pytest.mark.parametrize("bad_url", [1, None, [], {"nested": "x"}, True])
def test_a_non_string_url_does_not_raise(bad_url: Any) -> None:
    with pytest.raises(checker.VerificationError):
        checker.resolve_target(payload(tool_response={"url": bad_url}))


# An oversized decimal string: int() raises ValueError past
# sys.int_max_str_digits (4300 by default since CPython 3.11), and this
# repository's requires-python floor is >=3.12, so the limit always
# applies here.
_OVERSIZED_DIGITS = "7" * 5000


def test_an_oversized_url_number_is_indeterminate_not_a_traceback() -> None:
    """Reproduced before the guard: the conversion raised ValueError, which
    evaluate() does not catch (it catches VerificationError around
    resolution), so it escaped as a raw traceback -- contradicting this
    module's own "never a raw traceback" contract."""
    with pytest.raises(checker.VerificationError):
        checker.resolve_target(
            payload(tool_response={"url": f"https://github.com/tvna/gitapex/issues/{_OVERSIZED_DIGITS}"})
        )


def test_an_oversized_number_field_is_indeterminate_not_a_traceback() -> None:
    """The same conversion, on the pre-existing number-field path: both
    sources now share one guard rather than each converting on their own."""
    with pytest.raises(checker.VerificationError):
        checker.resolve_target(
            payload(tool_input={"owner": "tvna", "repo": "gitapex", "issue_number": _OVERSIZED_DIGITS})
        )


def test_an_oversized_first_url_field_falls_through_to_the_next() -> None:
    """An unusable value must not abort the search: `html_url` still
    resolves after `url` yields nothing."""
    resolved = checker.resolve_target(
        payload(
            tool_response={
                "url": f"https://github.com/tvna/gitapex/issues/{_OVERSIZED_DIGITS}",
                "html_url": "https://github.com/tvna/gitapex/issues/905",
            }
        )
    )
    assert resolved == ("tvna", "gitapex", 905)


def test_the_cli_reports_an_oversized_number_without_a_traceback(tmp_path: Path, capsys: Any) -> None:
    """End to end, through main(): the documented INDETERMINATE line, exit
    1, and no 'Traceback' anywhere in the output."""
    payload_file = tmp_path / "payload.json"
    payload_file.write_text(
        json.dumps(payload(tool_response={"url": f"https://github.com/tvna/gitapex/issues/{_OVERSIZED_DIGITS}"})),
        encoding="utf-8",
    )
    assert checker.main(["--payload", str(payload_file)]) == 1
    captured = capsys.readouterr()
    assert "INDETERMINATE" in captured.err
    assert "Traceback" not in captured.err + captured.out


def test_the_cli_reports_an_oversized_json_integer_literal_without_a_traceback(tmp_path: Path, capsys: Any) -> None:
    """The same oversized value as a JSON *integer literal* never reaches
    _positive_int: json.loads itself raises, and a plain ValueError at that
    -- json.JSONDecodeError is a ValueError subclass, not the other way
    round -- so the narrower handler let it escape as a raw traceback that
    the shell wrapper forwards verbatim as its block reason."""
    payload_file = tmp_path / "payload.json"
    payload_file.write_text(
        '{"tool_name": "mcp__github__issue_write", "tool_input": {"owner": "tvna", "repo": "gitapex", '
        f'"issue_number": {_OVERSIZED_DIGITS}}}}}',
        encoding="utf-8",
    )
    assert checker.main(["--payload", str(payload_file)]) == 1
    captured = capsys.readouterr()
    assert "INDETERMINATE" in captured.err
    assert "Traceback" not in captured.err + captured.out


# --- evaluate() verdicts --------------------------------------------------


@pytest.mark.parametrize(
    "tool_name",
    [
        "Bash",
        "mcp__github__merge_pull_request",
        "mcp__github__issue_read",
        "",
    ],
)
def test_an_uncovered_tool_skips(tool_name: str) -> None:
    verdict, _ = checker.evaluate(payload(tool_name=tool_name), "tok", fetcher=fetcher_returning(""))
    assert verdict == "SKIP"


@pytest.mark.parametrize("bad_name", [None, 5, [], {}])
def test_a_non_string_tool_name_skips_without_raising(bad_name: Any) -> None:
    verdict, _ = checker.evaluate({"tool_name": bad_name}, "tok", fetcher=fetcher_returning(""))
    assert verdict == "SKIP"


@pytest.mark.parametrize(
    "tool_name",
    [
        "mcp__github__create_pull_request",
        "mcp__github__update_pull_request",
        "mcp__github__issue_write",
    ],
)
def test_every_covered_tool_is_scanned(tool_name: str) -> None:
    verdict, _ = checker.evaluate(
        payload(
            tool_name=tool_name,
            tool_input={"owner": "tvna", "repo": "gitapex", "number": 1},
        ),
        "tok",
        fetcher=fetcher_returning("clean ASCII body\n"),
    )
    assert verdict == "PASS"


@pytest.mark.parametrize(
    "failure_marker",
    [{"status": "error"}, {"is_error": True}, {"isError": True}],
)
def test_a_failed_write_skips_rather_than_reporting_unverified(failure_marker: dict[str, Any]) -> None:
    response = {"number": 5, **failure_marker}
    verdict, _ = checker.evaluate(payload(tool_response=response), "tok", fetcher=fetcher_returning(_LEAKED_BODY))
    assert verdict == "SKIP"


@pytest.mark.parametrize(
    "failure_marker",
    [{"status": "error"}, {"is_error": True}, {"isError": True}],
)
def test_a_failed_write_skips_through_the_observed_bare_list_envelope(failure_marker: dict[str, Any]) -> None:
    """The marker sits inside the text block on the envelope the harness
    actually delivers, where _coerce_mapping sees only {}. Before this was
    fixed the branch was dead there and the call fell through to a scan."""
    response = [{"type": "text", "text": json.dumps({"number": 5, **failure_marker})}]
    verdict, _ = checker.evaluate(payload(tool_response=response), "tok", fetcher=fetcher_returning(_LEAKED_BODY))
    assert verdict == "SKIP"


def test_a_failed_create_does_not_report_on_the_url_in_its_error_payload() -> None:
    """The concrete consequence, reproduced before the fix: the URL fallback
    resolved a number out of a *failed* create's error payload and reported
    FLAGGED against a pre-existing, unrelated pull request that this call
    never wrote -- a block decision about the wrong artifact."""
    response = [
        {"type": "text", "text": json.dumps({"status": "error", "url": "https://github.com/tvna/gitapex/pull/884"})}
    ]
    verdict, _ = checker.evaluate(payload(tool_response=response), "tok", fetcher=fetcher_returning(_LEAKED_BODY))
    assert verdict == "SKIP"


def test_a_failed_update_does_not_report_on_the_targets_pre_existing_body() -> None:
    """The same defect on the update path, where the number comes from
    tool_input: the gate scanned the target's already-stored body and
    asserted a verdict about a write that never landed."""
    response = [{"type": "text", "text": json.dumps({"status": "error", "message": "boom"})}]
    verdict, _ = checker.evaluate(
        payload(
            tool_name="mcp__github__update_pull_request",
            tool_input={"owner": "tvna", "repo": "gitapex", "pullNumber": 884},
            tool_response=response,
        ),
        "tok",
        fetcher=fetcher_returning(_LEAKED_BODY),
    )
    assert verdict == "SKIP"


def test_an_mcp_level_error_flag_beside_a_content_list_still_skips() -> None:
    """The outer envelope's own marker must keep working: response_payload()
    returns the *inner* object for this shape, so checking only the
    normalized payload would have dropped a layer this gate already had."""
    verdict, _ = checker.evaluate(
        payload(
            tool_response={
                "isError": True,
                "content": [{"type": "text", "text": json.dumps({"number": 5})}],
            }
        ),
        "tok",
        fetcher=fetcher_returning(_LEAKED_BODY),
    )
    assert verdict == "SKIP"


def test_a_successful_status_is_still_scanned() -> None:
    verdict, _ = checker.evaluate(
        payload(tool_response={"number": 5, "status": "success"}),
        "tok",
        fetcher=fetcher_returning("clean\n"),
    )
    assert verdict == "PASS"


def test_the_same_fixture_that_trips_the_pre_write_scan_trips_this_path() -> None:
    """Issue #878's acceptance criterion: the post-write path must trip on
    the same content the pre-write scan trips on. Asserted against the
    shipped scanner itself, not a stub, so the two paths cannot drift."""
    scanner = checker.load_provenance_scanner()
    assert scanner.scan(_LEAKED_BODY), "fixture must trip the pre-write scan for this test to mean anything"

    verdict, message = checker.evaluate(
        payload(tool_response={"number": 5}), "tok", fetcher=fetcher_returning(_LEAKED_BODY)
    )
    assert verdict == "FLAGGED"
    assert "claude-example-model" in message
    assert "STORED body" in message


def test_a_non_ascii_only_body_is_flagged_too() -> None:
    verdict, message = checker.evaluate(
        payload(tool_response={"number": 5}),
        "tok",
        fetcher=fetcher_returning("Closes #878 \u2014 done\n"),
    )
    assert verdict == "FLAGGED"
    assert "U+2014" in message


def test_flagged_message_quotes_the_ratified_contributing_section_verbatim() -> None:
    """The FLAGGED path must not just point at CONTRIBUTING.md's ratified-
    trailer section -- it must quote that section's own text, so an
    operator applying the judgment call does not have to go open a second
    file to see the rule being applied. The pre-fix message only named the
    file/section, never its content."""
    verdict, message = checker.evaluate(
        payload(tool_response={"number": 5}), "tok", fetcher=fetcher_returning(_LEAKED_BODY)
    )
    assert verdict == "FLAGGED"
    # The existing judgment-call framing must survive unweakened.
    assert "This surfaces candidates; it does not decide." in message
    # The section's own text, not merely a pointer/filename reference.
    assert "agreed, disclosed convention" in message
    assert "issues/687" in message


def test_flagged_message_for_an_unratified_leak_does_not_claim_it_is_ratified() -> None:
    """A genuine, unratified leak -- a bare model identifier plus a
    session URL, but not CONTRIBUTING.md's specific 'Generated by ...
    during session ...' GitHub-appended trailer shape -- must still
    FLAG, and the message must never assert this particular hit IS the
    ratified one; it states the judgment call conditionally, same as
    before this fix."""
    body = (
        "See output from claude-sonnet-5 at https://claude.ai/code/session_01Unrelated12345 (a leak, not a trailer).\n"
    )
    scanner = checker.load_provenance_scanner()
    assert scanner.scan(body), "fixture must actually trip the scan for this test to mean anything"

    verdict, message = checker.evaluate(payload(tool_response={"number": 5}), "tok", fetcher=fetcher_returning(body))
    assert verdict == "FLAGGED"
    assert "if so, it is agreed" in message
    assert "Otherwise the content is already public" in message
    # The quoted section's own scope bullet states plainly that only the
    # GitHub-appended trailer is covered -- this hit is neither, and the
    # quoted text itself makes that explicit rather than the message
    # asserting it is ratified.
    assert "Does not cover a model identifier, session URL" in message


def test_flagged_message_falls_back_when_contributing_md_cannot_be_found(tmp_path: Path) -> None:
    """The injectable seam for CONTRIBUTING.md resolution, mirroring
    scanner_path's own injection pattern on load_provenance_scanner: when
    CONTRIBUTING.md cannot be found, the FLAGGED message still fires,
    still names the section, and never crashes."""
    verdict, message = checker.evaluate(
        payload(tool_response={"number": 5}),
        "tok",
        fetcher=fetcher_returning(_LEAKED_BODY),
        contributing_path=tmp_path / "absent-CONTRIBUTING.md",
    )
    assert verdict == "FLAGGED"
    assert "This surfaces candidates; it does not decide." in message
    assert "outward-artifact-preflight: PR-body trailer disclosure" in message
    assert "could not be located" in message


def test_the_draft_is_never_the_scan_input() -> None:
    """The submitted draft and the stored body are unrelated strings: the
    stored body does not contain the draft as a prefix, so this is real
    content loss (issue #1327) -- a stronger, more specific diagnosis than
    a bare FLAGGED. A check that scanned `tool_input.body` for provenance
    hits instead of comparing it against the re-fetched stored body would
    have reported PASS here (the draft text itself is clean); only
    comparing against what actually got stored catches it."""
    verdict, message = checker.evaluate(
        payload(
            tool_input={"owner": "tvna", "repo": "gitapex", "body": "totally clean draft"},
            tool_response={"number": 5},
        ),
        "tok",
        fetcher=fetcher_returning(_LEAKED_BODY),
    )
    assert verdict == "CONTENT_LOSS"
    assert "STORED body" in message


def test_a_missing_token_is_indeterminate_not_a_clean_pass() -> None:
    verdict, message = checker.evaluate(payload(tool_response={"number": 5}), None)
    assert verdict == "INDETERMINATE"
    assert "GH_TOKEN" in message


def test_an_api_failure_is_indeterminate_not_a_clean_pass() -> None:
    def failing_fetcher(owner: str, repo: str, number: int, token: str) -> dict[str, str]:
        raise pr_issue_checker.GitHubApiError("fetch-failed: HTTP 503")

    verdict, message = checker.evaluate(payload(tool_response={"number": 5}), "tok", fetcher=failing_fetcher)
    assert verdict == "INDETERMINATE"
    assert "503" in message


def test_a_non_github_api_error_is_indeterminate_not_a_traceback() -> None:
    """The shared fetch path parses its response with a bare json.loads, so
    a 2xx carrying a proxy interstitial raises JSONDecodeError -- a
    ValueError, not a GitHubApiError. Before this was caught it escaped
    every handler and surfaced through the wrapper as a raw traceback in
    the report's own reason field."""

    def decoding_fetcher(owner: str, repo: str, number: int, token: str) -> dict[str, str]:
        raise json.JSONDecodeError("Expecting value", "<html>not json</html>", 0)

    verdict, message = checker.evaluate(payload(tool_response={"number": 5}), "tok", fetcher=decoding_fetcher)
    assert verdict == "INDETERMINATE"
    assert "JSONDecodeError" in message
    assert "Traceback" not in message


def test_an_unexpected_error_class_is_also_indeterminate() -> None:
    def exploding_fetcher(owner: str, repo: str, number: int, token: str) -> dict[str, str]:
        raise RuntimeError("something nobody anticipated")

    verdict, message = checker.evaluate(payload(tool_response={"number": 5}), "tok", fetcher=exploding_fetcher)
    assert verdict == "INDETERMINATE"
    assert "RuntimeError" in message


@pytest.mark.parametrize("degenerate", [{}, {"body": ""}, {"body": "clean", "state": ""}, {"state": None}])
def test_a_response_that_is_not_an_issue_is_indeterminate_not_a_clean_pass(degenerate: dict[str, Any]) -> None:
    """A 2xx with an empty response body normalizes to {} in the shared
    fetch path. Scanning that as an empty string reported PASS -- the one
    place an inability to verify rendered as 'clean'."""

    def degenerate_fetcher(owner: str, repo: str, number: int, token: str) -> dict[str, Any]:
        return degenerate

    verdict, message = checker.evaluate(payload(tool_response={"number": 5}), "tok", fetcher=degenerate_fetcher)
    assert verdict == "INDETERMINATE"
    assert "no issue state" in message


def test_a_real_looking_response_still_passes() -> None:
    """The guard above must not turn every clean artifact into
    INDETERMINATE: a response carrying a real state scans normally."""
    verdict, _ = checker.evaluate(
        payload(tool_response={"number": 5}), "tok", fetcher=fetcher_returning("clean ASCII body")
    )
    assert verdict == "PASS"


def test_an_unresolvable_number_is_indeterminate_not_a_clean_pass() -> None:
    verdict, message = checker.evaluate(payload(tool_response={}), "tok", fetcher=fetcher_returning(""))
    assert verdict == "INDETERMINATE"
    assert "number" in message


def test_a_null_body_scans_as_empty_rather_than_crashing() -> None:
    def null_body_fetcher(owner: str, repo: str, number: int, token: str) -> dict[str, Any]:
        return {"body": None, "state": "open"}

    verdict, _ = checker.evaluate(payload(tool_response={"number": 5}), "tok", fetcher=null_body_fetcher)
    assert verdict == "PASS"


@pytest.mark.parametrize(
    "bad_body",
    [{"unexpected": "shape"}, ["a", "list"], 5, 5.5, True, False, 0, [], {}],
)
def test_a_non_string_body_is_indeterminate_not_a_crash(bad_body: Any) -> None:
    """`or ""` alone only coerces a falsy value; a truthy non-string body
    reached detect_content_loss()'s first `.replace()` call unguarded and
    crashed with a raw AttributeError before this guard existed -- found
    live by an adversarial gate-quality review of this issue's own change.
    The falsy non-string shapes (False, 0, [], {}) are a deliberate strength
    beyond that original finding: `or ""` alone would have silently
    normalized these to a clean PASS too, the same live review noted as an
    untested-but-correct strengthening once the isinstance guard replaced it."""

    def bad_body_fetcher(owner: str, repo: str, number: int, token: str) -> dict[str, Any]:
        return {"body": bad_body, "state": "open"}

    verdict, message = checker.evaluate(
        payload(
            tool_input={"owner": "tvna", "repo": "gitapex", "body": "some submitted text"},
            tool_response={"number": 5},
        ),
        "tok",
        fetcher=bad_body_fetcher,
    )
    assert verdict == "INDETERMINATE"
    assert "non-string body" in message


def test_content_loss_does_not_silently_mask_a_co_occurring_provenance_leak() -> None:
    """A stored body that is both truncated AND still carries a leaked
    marker in what remains must surface both defects, not just
    CONTENT_LOSS -- found live by the same adversarial gate-quality review:
    before this fix, scan_body() never ran once content loss was detected,
    so a co-occurring leak in the truncated remainder went unreported."""
    submitted = "Full original text with an important detail that must survive.\n\nRefs #1327"
    stored = "Full original text with an important \u2014 Generated by claude-example-model"
    verdict, message = checker.evaluate(
        payload(
            tool_input={"owner": "tvna", "repo": "gitapex", "body": submitted},
            tool_response={"number": 5},
        ),
        "tok",
        fetcher=fetcher_returning(stored),
    )
    assert verdict == "CONTENT_LOSS"
    assert "ALSO carries" in message
    assert "claude-example-model" in message
    assert "U+2014" in message


def test_content_loss_does_not_declare_a_ratified_looking_co_occurring_hit_an_unconditional_defect() -> None:
    """The co-occurring hit's own message must route to the same
    ratification judgment call the standalone FLAGGED path already gives,
    not declare it an automatic defect -- found live by a second
    adversarial gate-quality review: the first version of the 'ALSO
    carries' clause said 'both defects need remediation' unconditionally,
    which would misdirect an operator into stripping a ratified, agreed
    disclosure trailer (CONTRIBUTING.md's own documented example) rather
    than recognizing it as one."""
    submitted = "Full original text with an important detail that must survive.\n\nRefs #1327"
    stored = (
        "Full original text with an important \u2014 Generated by claude-example-model during "
        "session https://claude.ai/code/session_01Example99"
    )
    verdict, message = checker.evaluate(
        payload(
            tool_input={"owner": "tvna", "repo": "gitapex", "body": submitted},
            tool_response={"number": 5},
        ),
        "tok",
        fetcher=fetcher_returning(stored),
    )
    assert verdict == "CONTENT_LOSS"
    assert "ALSO carries" in message
    assert "judgment call" in message
    assert "ratified" in message
    assert "both defects" not in message


def test_content_loss_alone_does_not_claim_a_co_occurring_leak_that_is_not_there() -> None:
    """The inverse of the test above: a clean truncated remainder must not
    have the 'ALSO carries' clause appended -- it is conditional on a real
    co-occurring hit, not always present once loss fires."""
    submitted = "Full original text with an important detail that must survive.\n\nRefs #1327"
    stored = "Full original text with an important"
    verdict, message = checker.evaluate(
        payload(
            tool_input={"owner": "tvna", "repo": "gitapex", "body": submitted},
            tool_response={"number": 5},
        ),
        "tok",
        fetcher=fetcher_returning(stored),
    )
    assert verdict == "CONTENT_LOSS"
    assert "ALSO carries" not in message


def test_hit_reporting_is_capped_but_the_count_is_not() -> None:
    body = "\n".join("x\u2014" for _ in range(50))
    verdict, message = checker.evaluate(payload(tool_response={"number": 5}), "tok", fetcher=fetcher_returning(body))
    assert verdict == "FLAGGED"
    assert "50 non-ASCII character(s)" in message
    assert "and 30 more" in message


# --- content-loss detection, pure function (issue #1327) ------------------


def test_normalize_folds_crlf_to_lf() -> None:
    assert checker.normalize_for_content_loss("a\r\nb\r\n") == checker.normalize_for_content_loss("a\nb\n")


def test_normalize_strips_per_line_trailing_whitespace() -> None:
    assert checker.normalize_for_content_loss("a   \nb\t\n") == "a\nb"


def test_normalize_strips_trailing_blank_lines() -> None:
    assert checker.normalize_for_content_loss("a\nb\n\n\n") == "a\nb"


def test_identical_bodies_report_no_loss() -> None:
    assert checker.detect_content_loss("same text\n", "same text\n") is None


def test_crlf_normalization_alone_reports_no_loss() -> None:
    assert checker.detect_content_loss("line one\nline two\n", "line one\r\nline two\r\n") is None


def test_trailing_whitespace_normalization_alone_reports_no_loss() -> None:
    assert checker.detect_content_loss("line one\nline two", "line one   \nline two\t\n") is None


def test_an_empty_submitted_body_reports_no_loss() -> None:
    """Vacuous case: nothing was submitted, so nothing can be missing.
    evaluate() separately guards against ever calling this with an empty
    submitted_body (there is nothing to compare), but the pure function's
    own contract holds regardless."""
    assert checker.detect_content_loss("", "anything at all") is None


def test_an_append_only_addition_reports_no_loss() -> None:
    """The ratified-attribution-trailer shape: `stored` is `submitted`
    plus something appended after it -- the exact shape
    outward-artifact-preflight/SKILL.md's own worked example describes.
    This comparison must stay silent; the provenance scan owns the
    judgment call on whether the addition itself is a leak."""
    submitted = "fix(skill): tighten the ordering rule\n\nRefs #83"
    stored = (
        submitted + "\n\nGenerated by claude-example-model during session https://claude.ai/code/session_01Example99"
    )
    assert checker.detect_content_loss(submitted, stored) is None


def test_content_missing_from_the_end_is_loss() -> None:
    """Genuine truncation: the tail of the submitted body never made it
    into storage."""
    submitted = "Full original text with an important detail.\n\nRefs #1327"
    stored = "Full original text with an important"
    assert checker.detect_content_loss(submitted, stored) is not None


def test_content_missing_from_the_start_is_loss() -> None:
    """Adversarial/defeat-test case: a naive "is either string a substring
    of the other" check would wrongly call this safe, since `stored` is a
    substring of `submitted` here too. The real shape is a stripped
    leading header -- real content loss -- and tolerating it would
    silently defeat the whole check for any loss that does not happen to
    land at the very end. This is the case this module's own
    prefix-only (not substring) comparison exists to still catch."""
    submitted = "IMPORTANT NOTICE\n\nFull original text with an important detail."
    stored = "Full original text with an important detail."
    assert checker.detect_content_loss(submitted, stored) is not None


def test_content_missing_from_the_middle_is_loss() -> None:
    submitted = "Part one.\n\nPart two, the important part.\n\nPart three."
    stored = "Part one.\n\nPart three."
    assert checker.detect_content_loss(submitted, stored) is not None


def test_the_angle_bracket_placeholder_shape_is_not_loss_via_the_raw_channel() -> None:
    """Issue #1088's own repair 2 fixture, re-run against this hook's own
    raw-fetch channel (what `stored` represents here): the corrected
    diagnosis holds -- GitHub's storage never actually stripped it, so
    there is nothing here for this comparison to flag."""
    body = "Each gets a `<ScriptName>Args(BaseModel)` model.\n\nRefs #1088"
    assert checker.detect_content_loss(body, body) is None


def test_the_autolink_shape_is_not_loss_via_the_raw_channel() -> None:
    """Issue #1313's own repair 1 fixture, same corrected-diagnosis logic:
    a bracket-wrapped-URL autolink is intact in a raw, unsanitized fetch."""
    body = "See <https://github.com/tvna/gitapex/issues/1135> for the prior discussion.\n\nRefs #1313"
    assert checker.detect_content_loss(body, body) is None


# --- content-loss verdict via evaluate() (issue #1327) ---------------------


def test_evaluate_reports_content_loss_for_genuine_truncation() -> None:
    submitted = "Full original text with an important detail that must survive.\n\nRefs #1327"
    stored = "Full original text with an important"
    verdict, message = checker.evaluate(
        payload(
            tool_input={"owner": "tvna", "repo": "gitapex", "body": submitted},
            tool_response={"number": 5},
        ),
        "tok",
        fetcher=fetcher_returning(stored),
    )
    assert verdict == "CONTENT_LOSS"
    assert "missing content" in message
    assert "pull_request_read" in message


def test_evaluate_skips_content_loss_check_when_tool_input_carries_no_body() -> None:
    """The default payload() helper's tool_input carries owner/repo only --
    every pre-existing FLAGGED/PASS test relies on this staying a silent
    skip, not a forced comparison against an empty string."""
    verdict, _ = checker.evaluate(
        payload(tool_response={"number": 5}), "tok", fetcher=fetcher_returning("clean ASCII body\n")
    )
    assert verdict == "PASS"


def test_evaluate_does_not_flag_content_loss_for_a_non_string_body_field() -> None:
    """A malformed/unexpected tool_input.body (e.g. a list) must not crash
    or be misread as a submission -- only a real, non-empty string is ever
    compared."""
    verdict, _ = checker.evaluate(
        payload(
            tool_input={"owner": "tvna", "repo": "gitapex", "body": ["not", "a", "string"]},
            tool_response={"number": 5},
        ),
        "tok",
        fetcher=fetcher_returning("clean ASCII body\n"),
    )
    assert verdict == "PASS"


def test_an_append_only_trailer_is_not_content_loss_but_still_flags_provenance() -> None:
    """The append-only shape must not report CONTENT_LOSS -- that stays
    the provenance scan's own judgment call -- but a real provenance hit
    inside the addition must still surface as FLAGGED, unchanged from
    before this issue's own comparison existed."""
    submitted = "fix(skill): tighten the ordering rule\n\nRefs #83"
    stored = (
        submitted + "\n\nGenerated by claude-example-model during session https://claude.ai/code/session_01Example99"
    )
    verdict, message = checker.evaluate(
        payload(
            tool_input={"owner": "tvna", "repo": "gitapex", "body": submitted},
            tool_response={"number": 5},
        ),
        "tok",
        fetcher=fetcher_returning(stored),
    )
    assert verdict == "FLAGGED"
    assert "claude-example-model" in message


def test_an_intact_angle_bracket_placeholder_body_passes_clean_end_to_end() -> None:
    """The corrected diagnosis, exercised through evaluate() rather than
    the pure function directly: a submitted body reproducing #1088's own
    shape, fetched back unchanged (as the real raw channel does), reports
    PASS -- neither CONTENT_LOSS nor FLAGGED."""
    body = "Each gets a `<ScriptName>Args(BaseModel)` model.\n\nRefs #1088"
    verdict, _ = checker.evaluate(
        payload(
            tool_input={"owner": "tvna", "repo": "gitapex", "body": body},
            tool_response={"number": 5},
        ),
        "tok",
        fetcher=fetcher_returning(body),
    )
    assert verdict == "PASS"


# --- main() ---------------------------------------------------------------


def test_main_reports_indeterminate_on_a_non_object_payload(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.setattr("sys.stdin", _StringStdin("[1, 2, 3]"))
    assert checker.main([]) == 1
    assert "INDETERMINATE" in capsys.readouterr().err


def test_main_reports_indeterminate_on_invalid_json(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.setattr("sys.stdin", _StringStdin("not json at all"))
    assert checker.main([]) == 1
    assert "INDETERMINATE" in capsys.readouterr().err


def test_main_skips_an_empty_payload(monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]) -> None:
    monkeypatch.setattr("sys.stdin", _StringStdin(""))
    assert checker.main([]) == 0
    assert "SKIP" in capsys.readouterr().out


def test_main_reports_a_missing_payload_file(capsys: pytest.CaptureFixture[str]) -> None:
    assert checker.main(["--payload", str(REPO_ROOT / "no-such-payload.json")]) == 1
    assert "not found" in capsys.readouterr().err


def test_main_reads_a_payload_file(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    path = tmp_path / "payload.json"
    path.write_text(json.dumps({"tool_name": "Bash"}), encoding="utf-8")
    assert checker.main(["--payload", str(path)]) == 0
    assert "SKIP" in capsys.readouterr().out


def test_a_spec_that_will_not_load_is_indeterminate(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """importlib can return a spec with no loader for a path it recognizes
    but cannot execute. That must reach the INDETERMINATE path, not raise
    an AttributeError on `spec.loader.exec_module`."""
    target = tmp_path / "loadable.py"
    target.write_text("x = 1\n", encoding="utf-8")
    monkeypatch.setattr(checker.importlib.util, "spec_from_file_location", lambda *a, **k: None)
    with pytest.raises(checker.VerificationError) as excinfo:
        checker.load_provenance_scanner(target)
    assert "could not be loaded" in str(excinfo.value)


def test_provenance_hit_reporting_is_capped_but_the_count_is_not() -> None:
    """The ASCII half's cap is covered above; this covers the provenance
    half's own truncation branch, which is a separate code path."""
    body = "\n".join(f"Generated by tool-{index}" for index in range(25))
    verdict, message = checker.evaluate(payload(tool_response={"number": 5}), "tok", fetcher=fetcher_returning(body))
    assert verdict == "FLAGGED"
    assert "25 candidate provenance marker(s)" in message
    assert "and 5 more" in message


def test_the_default_fetcher_delegates_to_the_shared_hook_helper(monkeypatch: pytest.MonkeyPatch) -> None:
    """evaluate()'s default fetcher must be the already-tested
    hooks/gitapex_check_pr_issue_acm_disclosure.py helper, not a second
    copy of the retry/backoff logic."""
    seen: dict[str, object] = {}

    def fake_fetch_issue(owner: str, repo: str, number: int, token: str) -> dict[str, str]:
        seen.update({"owner": owner, "repo": repo, "number": number, "token": token})
        return {"body": "clean", "state": "open"}

    monkeypatch.setattr(pr_issue_checker, "fetch_issue", fake_fetch_issue)
    verdict, _ = checker.evaluate(payload(tool_response={"number": 5}), "tok")
    assert verdict == "PASS"
    assert seen == {"owner": "tvna", "repo": "gitapex", "number": 5, "token": "tok"}


def test_main_reports_a_non_utf8_payload_file(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    path = tmp_path / "payload.json"
    path.write_bytes(b'{"tool_name": "\xff\xfe"}')
    assert checker.main(["--payload", str(path)]) == 1
    assert "not valid UTF-8" in capsys.readouterr().err


def test_main_exits_one_and_reports_on_stderr_for_an_unverifiable_target(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    """A covered tool whose target cannot be resolved never reaches the
    network, so this exercises main()'s own non-zero exit path without a
    fetch."""
    monkeypatch.setattr(
        "sys.stdin",
        _StringStdin(json.dumps({"tool_name": "mcp__github__create_pull_request", "tool_input": {}})),
    )
    assert checker.main([]) == 1
    assert "INDETERMINATE" in capsys.readouterr().err


class _StringStdin:
    def __init__(self, data: str) -> None:
        self._data = data

    def read(self) -> str:
        return self._data
