"""Regression suite for check-pr-body-preflight.sh's own deny/allow matrix
(issue #1725).

Named `_shell` for the same pytest-basename reason
hooks/test_gitapex_check_pr_issue_acm_disclosure_shell.py documents: both
`tests/` and `hooks/` are on pyproject.toml's `testpaths` with no
`__init__.py` in either, so two files sharing a basename fail collection.

This hook's own bash logic (base-branch/merge-base resolution, the
stacked-PR narrowing, the fail-open/fail-closed split, the empty-body
bypass) had no automated coverage at all before two rounds of independent
adversarial review of this issue's own implementation found several real
defects in it -- a stacked-PR false-deny risk, a fail-open policy
inversion relative to the sibling hooks/check-pr-skill-audit-disclosure.sh,
an old-bash-incompatible empty-array expansion, and an inaccurate
"skipped" claim about provenance-disclosure's own body-only mode among
them -- all fixed and pinned here, mirroring that sibling's own
test_gitapex_check_pr_skill_audit_disclosure_shell.py test shape.

Each test runs the shipped script via subprocess with the PreToolUse JSON
shape Claude Code sends on stdin, against a scratch git repository built
to trigger one specific path.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

import pytest

SCRIPT = Path(__file__).parent / "check-pr-body-preflight.sh"
REPO_ROOT = Path(__file__).parent.parent

pytestmark = pytest.mark.slow

_PREFLIGHT_FILES = (
    ".github/scripts/gitapex_gate_pr_body_preflight.py",
    ".github/scripts/gitapex_gate_provenance_disclosure.py",
    ".github/scripts/gitapex_extract_diff_added_lines.py",
    "skills/outward-artifact-preflight/scripts/gitapex_scan_provenance.py",
)

_HOOK_FILES = ("hooks/check-pr-body-preflight.sh",)

_CLEAN_BODY = "Clean PR body.\n\nCloses #1725\n"
_NON_ASCII_BODY = "Body with a café in it.\n"
_PROVENANCE_MARKER_BODY = "Generated by claude-code for this change.\n"

# Issue #1711's own reconstruction (see tests/test_gitapex_gate_pr_body_
# preflight.py's own _1711_BODY): a limitation cue and a tool-fingerprint
# cue combined in one paragraph.
_PROVENANCE_DISCLOSURE_BODY = (
    "Execution log bullet: skill-audit-disclosure found the body missing "
    "its required section, because no access to a registered skill "
    "invocation was available for a dispatch tool at the time.\n"
)


def _git(repo: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(["git", "-C", str(repo), *args], check=True, capture_output=True, text=True)


def _write(repo: Path, relative: str, content: str = "x\n") -> None:
    path = repo / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _copy(repo: Path, relative: str) -> None:
    _write(repo, relative, (REPO_ROOT / relative).read_text(encoding="utf-8"))


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    """A scratch repo with a `main` branch published as `origin/main`
    (what the hook resolves its base branch against), carrying every
    script the preflight it wraps depends on."""
    subprocess.run(["git", "init", "-q", "-b", "main", str(tmp_path)], check=True)
    _git(tmp_path, "config", "user.email", "t@e")
    _git(tmp_path, "config", "user.name", "t")
    for relative in (*_HOOK_FILES, *_PREFLIGHT_FILES):
        _copy(tmp_path, relative)
    _write(tmp_path, "README.md")
    _git(tmp_path, "add", "-A")
    _git(tmp_path, "commit", "-qm", "base")
    # A local `origin` remote so `git merge-base origin/main HEAD` resolves
    # without network access. `set-head` matters: without
    # refs/remotes/origin/HEAD the default-branch fallback resolves to
    # nothing and the hook exits early, passing every no-explicit-base
    # test for the wrong reason.
    _git(tmp_path, "remote", "add", "origin", str(tmp_path))
    _git(tmp_path, "fetch", "-q", "origin")
    _git(tmp_path, "remote", "set-head", "origin", "main")
    _git(tmp_path, "checkout", "-q", "-b", "feature")
    return tmp_path


def _publish(repo: Path) -> None:
    """Push the current feature branch's own commits to origin/main, so a
    later `git merge-base origin/main HEAD` on a *different* branch sees
    them -- used to build a stacked-PR fixture."""
    _git(repo, "checkout", "-q", "main")
    _git(repo, "merge", "-q", "feature")
    _git(repo, "push", "-q", "origin", "main")
    _git(repo, "checkout", "-q", "feature")


def _commit(repo: Path, message: str = "change") -> None:
    _git(repo, "add", "-A")
    _git(repo, "commit", "-qm", message)


def _run(
    repo: Path, body: str, tool_name: str = "mcp__github__create_pull_request", base: str | None = "main"
) -> subprocess.CompletedProcess[str]:
    tool_input: dict[str, str] = {"body": body}
    if base is not None:
        tool_input["base"] = base
    payload = json.dumps({"tool_name": tool_name, "tool_input": tool_input})
    return subprocess.run(
        ["bash", str(repo / "hooks" / "check-pr-body-preflight.sh")],
        input=payload,
        capture_output=True,
        text=True,
        timeout=60,
        cwd=str(repo),
    )


# --- happy path / deny on each sub-check ---


def test_allows_a_clean_body(repo: Path) -> None:
    result = _run(repo, _CLEAN_BODY)
    assert result.returncode == 0, result.stderr


def test_denies_a_non_ascii_body(repo: Path) -> None:
    result = _run(repo, _NON_ASCII_BODY)
    assert result.returncode == 2, result.stderr
    assert "ascii-only" in result.stderr


def test_denies_a_body_carrying_a_provenance_marker(repo: Path) -> None:
    result = _run(repo, _PROVENANCE_MARKER_BODY)
    assert result.returncode == 2, result.stderr
    assert "provenance-marker-scan" in result.stderr


def test_denies_a_body_reconstructing_1711(repo: Path) -> None:
    result = _run(repo, _PROVENANCE_DISCLOSURE_BODY)
    assert result.returncode == 2, result.stderr
    assert "provenance-disclosure" in result.stderr


def test_deny_names_the_local_re_check_command(repo: Path) -> None:
    result = _run(repo, _NON_ASCII_BODY)
    assert result.returncode == 2
    assert "gitapex_gate_pr_body_preflight.py" in result.stderr
    assert "--check-diff" in result.stderr


def test_skill_audit_disclosure_is_always_skipped_by_this_hook(repo: Path) -> None:
    """hooks/check-pr-skill-audit-disclosure.sh already owns that gate on
    the identical matchers -- a diff adding a SKILL.md with no disclosure
    at all must still be allowed here, since --skip skill-audit-disclosure
    means this hook never runs that sub-check."""
    _write(repo, "skills/sample/SKILL.md", "---\nname: sample\ndescription: x\n---\n\nBody.\n")
    _commit(repo, "new skill, no disclosure")
    result = _run(repo, "no evidence section at all")
    assert result.returncode == 0, result.stderr


# --- fail CLOSED when the preflight script itself crashes (issue #1725
# review finding: this hook previously failed open here) ---


def test_denies_when_the_preflight_script_itself_crashes(repo: Path) -> None:
    _write(repo, ".github/scripts/gitapex_gate_pr_body_preflight.py", "this is not valid python(((")
    _commit(repo, "corrupt the preflight script itself")
    result = _run(repo, _CLEAN_BODY)
    assert result.returncode == 2, result.stderr
    assert "without a recognized 'FAIL ' line" in result.stderr
    assert "bug in the check script itself" in result.stderr


def test_denies_even_when_the_crash_output_is_large(repo: Path) -> None:
    """Regression: the FAIL-detection grep must read its input to
    completion (same pipefail hazard hooks/check-pr-skill-audit-
    disclosure.sh's own suite already pins)."""
    huge_traceback = "raise RuntimeError('x' * 20000)\n"
    _write(repo, ".github/scripts/gitapex_gate_pr_body_preflight.py", huge_traceback)
    _commit(repo, "make the preflight script crash noisily")
    result = _run(repo, _CLEAN_BODY)
    assert result.returncode == 2, result.stderr
    assert "without a recognized 'FAIL ' line" in result.stderr


# --- fail OPEN only on genuinely inconclusive local git state ---


def test_falls_through_when_the_preflight_script_is_absent(repo: Path) -> None:
    """Plugin-only install: .github/ never ships, per docs/repository-
    layout.md."""
    (repo / ".github" / "scripts" / "gitapex_gate_pr_body_preflight.py").unlink()
    _commit(repo, "remove .github/ (plugin-only install)")
    result = _run(repo, _NON_ASCII_BODY)
    assert result.returncode == 0, result.stderr


def test_warns_and_allows_when_origin_base_is_unresolvable(repo: Path) -> None:
    result = _run(repo, _NON_ASCII_BODY, base="does-not-exist-upstream")
    assert result.returncode == 0, result.stderr
    assert "could not resolve origin/does-not-exist-upstream" in result.stderr


def test_falls_through_to_exit_0_when_mktemp_is_broken(
    repo: Path, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("TMPDIR", str(tmp_path / "does-not-exist"))
    result = _run(repo, _CLEAN_BODY)
    assert result.returncode == 0, result.stderr
    assert "mktemp failed" in result.stderr


def test_outside_a_git_work_tree_the_hook_stays_out_of_the_way(tmp_path: Path) -> None:
    for relative in _HOOK_FILES:
        target = tmp_path / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text((REPO_ROOT / relative).read_text(encoding="utf-8"), encoding="utf-8")
    result = subprocess.run(
        ["bash", str(tmp_path / "hooks" / "check-pr-body-preflight.sh")],
        input=json.dumps({"tool_name": "mcp__github__create_pull_request", "tool_input": {"body": ""}}),
        capture_output=True,
        text=True,
        timeout=60,
        cwd=str(tmp_path),
    )
    assert result.returncode == 0


# --- the stacked-PR false-deny fix (issue #1725 review finding) ---


def test_stacked_pr_with_no_explicit_base_drops_check_diff(repo: Path) -> None:
    """A parent feature branch's own change (one origin/main does not have
    yet -- never published, unlike _publish()'s own tier-1 precedent) must
    not be dragged into --check-diff's scope for an update_pull_request
    call that supplies no explicit base -- drops --check-diff entirely
    instead of denying against the wrong ancestor.

    Deliberately does NOT publish the parent branch's own change to
    origin/main before forking the stacked branch: an earlier version of
    this fixture called _publish() first, which meant origin/main already
    had the parent's change and `git merge-base origin/main HEAD` computed
    the *same* (correct) ancestor with or without this fix -- a false
    reassurance the fix's own review caught. This fixture instead proves
    the risk is real before checking the fix at all: the wrong-ancestor
    diff (origin/main, which the fix's absence would fall back to) is
    shown below to genuinely include the parent branch's own
    provenance-disclosure-triggering paragraph, which the real ancestor
    (`feature`) would not."""
    _write(repo, "docs/notes.md", _PROVENANCE_DISCLOSURE_BODY)
    _commit(repo, "parent branch: docs change that would trip provenance-disclosure")
    # A second, real feature branch stacked on top of the one just
    # committed (never pushed to origin) -- its own real base is
    # "feature", not "main", but this call supplies no explicit base at
    # all.
    _git(repo, "checkout", "-q", "-b", "feature-2")
    _write(repo, "README.md", "stacked change\n")
    _commit(repo, "stacked PR's own change")

    # Prove the risk this fixture reconstructs is real: the wrong-ancestor
    # diff (what a base_is_explicit-unaware hook would compute against)
    # actually does sweep in the parent branch's own unrelated change.
    wrong_ancestor_diff = _git(repo, "diff", "origin/main...feature-2", "--", "docs/notes.md").stdout
    assert "no access to a registered skill" in wrong_ancestor_diff, (
        "fixture bug: the wrong-ancestor diff does not actually include the parent branch's own "
        "provenance-disclosure-triggering change -- this test would pass even without the fix"
    )

    result = _run(repo, _CLEAN_BODY, tool_name="mcp__github__update_pull_request", base=None)
    assert result.returncode == 0, result.stderr
    assert "dropping --check-diff" in result.stderr


def test_create_pull_request_always_supplies_base_and_keeps_full_coverage(repo: Path) -> None:
    """create_pull_request always sends tool_input.base, so base_is_explicit
    stays yes and the diff-dependent sub-check still runs -- this narrowing
    must not blanket-disable --check-diff."""
    result = _run(repo, _PROVENANCE_DISCLOSURE_BODY, tool_name="mcp__github__create_pull_request", base="main")
    assert result.returncode == 2, result.stderr
    assert "provenance-disclosure" in result.stderr
    assert "dropping --check-diff" not in result.stderr


def test_update_pull_request_with_an_explicit_base_keeps_full_coverage(repo: Path) -> None:
    result = _run(repo, _PROVENANCE_DISCLOSURE_BODY, tool_name="mcp__github__update_pull_request", base="main")
    assert result.returncode == 2, result.stderr
    assert "provenance-disclosure" in result.stderr
    assert "dropping --check-diff" not in result.stderr


# --- shared guards ---


def test_an_unrelated_tool_call_is_ignored(repo: Path) -> None:
    result = _run(repo, _NON_ASCII_BODY, tool_name="mcp__github__add_issue_comment")
    assert result.returncode == 0


def test_an_update_call_with_no_body_is_ignored(repo: Path) -> None:
    payload = json.dumps({"tool_name": "mcp__github__update_pull_request", "tool_input": {"base": "main"}})
    result = subprocess.run(
        ["bash", str(repo / "hooks" / "check-pr-body-preflight.sh")],
        input=payload,
        capture_output=True,
        text=True,
        timeout=60,
        cwd=str(repo),
    )
    assert result.returncode == 0


def test_a_create_call_with_an_empty_body_still_runs_the_preflight(repo: Path) -> None:
    """Only update_pull_request gets the empty-body bypass -- a create call
    with an empty body still goes through the preflight script (a
    guaranteed PASS here, since every sub-check this hook runs trivially
    passes an empty body, but the invocation itself must still happen)."""
    result = _run(repo, "", tool_name="mcp__github__create_pull_request", base="main")
    assert result.returncode == 0, result.stderr


# ---------------------------------------------------------------------------
# Issue #1208's own jq-missing / malformed-payload fail-closed guards, same
# shape as hooks/check-pr-skill-audit-disclosure.sh's own suite.
# ---------------------------------------------------------------------------


def _no_jq_path(tmp_path: Path) -> str:
    bin_dir = tmp_path / "no-jq-path"
    bin_dir.mkdir()
    for tool in ("bash", "cat", "git", "python3", "dirname", "mktemp"):
        real = shutil.which(tool)
        if real:
            (bin_dir / tool).symlink_to(real)
    return str(bin_dir)


def test_denied_when_jq_missing(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("PATH", _no_jq_path(tmp_path))
    payload = json.dumps({"tool_name": "mcp__github__create_pull_request", "tool_input": {"base": "main", "body": ""}})
    result = subprocess.run(
        ["bash", str(REPO_ROOT / "hooks" / "check-pr-body-preflight.sh")],
        input=payload,
        capture_output=True,
        text=True,
        timeout=60,
        cwd=str(REPO_ROOT),
    )
    assert result.returncode == 2, f"expected deny (exit 2), got {result.returncode}: stderr={result.stderr!r}"
    parsed = json.loads(result.stderr)
    assert parsed["hookSpecificOutput"]["permissionDecision"] == "deny"
    assert "jq is not available" in parsed["systemMessage"]


def test_denied_on_malformed_json_stdin() -> None:
    result = subprocess.run(
        ["bash", str(REPO_ROOT / "hooks" / "check-pr-body-preflight.sh")],
        input="not valid json{{{",
        capture_output=True,
        text=True,
        timeout=60,
        cwd=str(REPO_ROOT),
    )
    assert result.returncode == 2, f"expected deny (exit 2), got {result.returncode}: stderr={result.stderr!r}"
    parsed = json.loads(result.stderr)
    assert parsed["hookSpecificOutput"]["permissionDecision"] == "deny"


@pytest.mark.parametrize(
    "tool_input",
    [["not", "an", "object"], "text", False, True, 0],
    ids=["array", "string", "false", "true", "zero"],
)
def test_denied_when_tool_input_is_not_an_object(tool_input: object) -> None:
    payload = json.dumps({"tool_name": "mcp__github__create_pull_request", "tool_input": tool_input})
    result = subprocess.run(
        ["bash", str(REPO_ROOT / "hooks" / "check-pr-body-preflight.sh")],
        input=payload,
        capture_output=True,
        text=True,
        timeout=60,
        cwd=str(REPO_ROOT),
    )
    assert result.returncode == 2, f"expected deny (exit 2) for tool_input={tool_input!r}, got {result.returncode}"
    parsed = json.loads(result.stderr)
    assert parsed["hookSpecificOutput"]["permissionDecision"] == "deny"


@pytest.mark.parametrize(
    "tool_name",
    [["mcp__github__create_pull_request"], {"x": 1}, 5, True],
    ids=["array", "object", "number", "bool"],
)
def test_denied_when_tool_name_is_not_a_string(tool_name: object) -> None:
    payload = json.dumps({"tool_name": tool_name, "tool_input": {"base": "main", "body": "no evidence"}})
    result = subprocess.run(
        ["bash", str(REPO_ROOT / "hooks" / "check-pr-body-preflight.sh")],
        input=payload,
        capture_output=True,
        text=True,
        timeout=60,
        cwd=str(REPO_ROOT),
    )
    assert result.returncode == 2, f"expected deny (exit 2) for tool_name={tool_name!r}, got {result.returncode}"
    parsed = json.loads(result.stderr)
    assert parsed["hookSpecificOutput"]["permissionDecision"] == "deny"


def test_denied_on_valid_json_non_object_stdin() -> None:
    result = subprocess.run(
        ["bash", str(REPO_ROOT / "hooks" / "check-pr-body-preflight.sh")],
        input="[]",
        capture_output=True,
        text=True,
        timeout=60,
        cwd=str(REPO_ROOT),
    )
    assert result.returncode == 2, f"expected deny (exit 2), got {result.returncode}: stderr={result.stderr!r}"
    parsed = json.loads(result.stderr)
    assert parsed["hookSpecificOutput"]["permissionDecision"] == "deny"
